### ISSUE TITLE
Allow setting default upload target per-account

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#100]
At least for my company we don't use the "private" target at all.  Would you consider to let me configure company wide to set the default to "embargo" rather than "private"?

Would mean a few less clicks at least.  Obviously really low priority.

**Comment by hughsie** [comment]
Set the default, or remove "private" from the drop down when logged in as Dell? If you don't want people to use it it seems better to just remove the upload location drop-down completely.

**Comment by superm1** [comment]
Good point, I think removing it completely is better.

**Comment by hughsie** [comment]
Is this per-vendor (i.e. for all the Dell ODMs) or per user (i.e. for a specific ODM)?

**Comment by superm1** [comment]
per-vendor
