### ISSUE TITLE
Missing firmware update : Inspiron 15 7000 Gaming

### ISSUE THREAD

**Issue by kaipee** [hughsie/lvfs-website#103]
For missing firmware please provide the following items:

* Link to firmware update at OEM website
https://www.dell.com/support/home/uk/en/ukbsdt1/drivers/driversdetails?driverId=KX8XM

* Firmware release date (if available on OEM website)
18 Feb 2018

* Link to the device page on LVFS.
https://fwupd.org/lvfs/device/1610b70e-2db1-41d0-bcaf-19ad38fff695

**Comment by kaipee** [comment]
Thanks, I have already updated the firmware on my device manually (a separate /boot/Dell partition onto which I place the files, then F12 > Update firmware) - which is how I noticed LVFS was missing the latest file.

**Comment by superm1** [comment]
OK thanks for confirming you could update successfully.

**Comment by superm1** [comment]
1.6.0 is available now.
