### ISSUE TITLE
Missing Dell XPS 9350 BIOS update

### ISSUE THREAD

**Issue by martey** [hughsie/lvfs-website#106]
The Dell website lists 1.7.0 as the latest version, but LVFS only has 1.6.1.

* Link to firmware update at OEM website: http://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverId=CXXJM
* Firmware release date: 21 March 2018
* Link to the device page on LVFS: https://fwupd.org/lvfs/device/33773727-8ee7-4d81-9fa0-57e8d889e1fa

**Comment by superm1** [comment]
It's up there now.
