### ISSUE TITLE
LVFS Computer hardware IDs doesn't behave as expected

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#110]
The current U/I for CHIDs allows you to apply multiple hardware IDs, but those HWIDs are treated as *AND* rather than *OR*.  The similar U/I in WU treats them as *AND* so this is a confusing experience to folks uploading.

At least one FW has been affected that two CHIDs were set intending to go to two machines but the end result was the FW wasn't offered to either machine since it's impossible to meet both CHID requirements.

So I'd like to see the UX changed to match the WU approach where multiple HWIDs default to "OR".  This means creating a regex for the requirements around HWIDs.

**Comment by superm1** [comment]
> According to https://fwupd.org/lvfs/firmware/551 it's been downloaded 2271 times, so I'm not sure how that's happened.

Theory: running on older fwupd (or fwupd compiled against older appstream-glib) that wasn't enforcing HWID checks.

> which means also fixing fwupd to split that before matching. Sane?

I wish fwupd 1.0.7 hadn't "just dropped" in that situation so we could get a version with this type of fix out together.  Although it sounds like there might not really be a no-client changes solution from your above description.

**Comment by hughsie** [comment]
> that wasn't enforcing HWID checks

Maybe anything compiled against the old version of appstream-glib?

> I wish fwupd 1.0.7 hadn't "just dropped"

There's always "just one more bug" -- and I can do a new release next week if required. Releases are cheap.

**Comment by superm1** [comment]
> Maybe anything compiled against the old version of appstream-glib?

I think that looks like a believable root cause.  At least the "recent" downloads I see are gnome-software with no fwupd version reported which could mean Ubuntu 16.04's fwupd / gnome-software.

> There's always "just one more bug" -- and I can do a new release next week if required. Releases are cheap.

Well but client changes means that stuff like RHEL is broken and can't be fixed for a while :/

**Comment by hughsie** [comment]
> can't be fixed for a while

Nothing official but 7.6 is coming up and I feel good things.
