### ISSUE TITLE
Wrong firmware is listed for Thunderbolt NVM for Xps Notebook 9550

### ISSUE THREAD

**Issue by vcatalano** [hughsie/lvfs-website#113]
From the devices page (https://fwupd.org/lvfs/devicelist) select **Thunderbolt NVM for Xps Notebook 9550** link. This takes you to the **Thunderbolt NVM for Xps Notebook 9250** page instead of the **Thunderbolt NVM for Xps Notebook 9550** page.

**Comment by hughsie** [comment]
It's actually the same firmware for 10 different devices, so I believe we just show the "first" device in the component list that matches the GUID. I do agree it's confusing.

**Comment by vcatalano** [comment]
Thanks for the clarification!
