### ISSUE TITLE
Missing firmware: Dell 5x80 / Precision 3520 BIOS 1.9.3

### ISSUE THREAD

**Issue by sjbarag** [hughsie/lvfs-website#115]
For missing firmware please provide the following items:

### Link to firmware update at OEM website
http://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverId=D5GH9 (direct `.exe` download: https://downloads.dell.com/FOLDER04862512M/1/Latitude_5X80_Precision_3520_1.9.3.exe)

### Firmware release date (if available on OEM website)
Released on March 15, 2018

### Link to the device page on LVFS.
(Several GUIDs seem to match here?)
* https://fwupd.org/lvfs/device/8b7b32a7-0dee-4851-9707-ee7e8c2c4881 &mdash; my system specifcially
* https://fwupd.org/lvfs/device/49e03513-7afe-498a-9d03-89e5ba1da865 &mdash; also listed on LVFS as the Latitude E5X80

This firmware drop was particularly helpful because of a bugfix included in it:

> Fixed the internal keyboard fast typing character loss or repeating issue that occurred at very high words per minute (WPM) typing speed.

**Comment by sjbarag** [comment]
If you're busy, let me know how I can help! :smile:

**Comment by superm1** [comment]
Thanks it should be there now.

**Comment by sjbarag** [comment]
@superm1 Thanks!  Confirmed to be available via `fwupdmgr`.

Side-note: this was my first time using `fwupdmgr` and the update went flawlessly &mdash; I can't possibly thank you, @hughsie, and every other contributor enough.  Fantastic work :heart:
