### ISSUE TITLE
HP Pavilion g7-2200 series

### ISSUE THREAD

**Issue by FireWolf74** [hughsie/lvfs-website#118]
For missing firmware please provide the following items:
pretty much i need a camera driver for this laptop.
* Link to firmware update at OEM website
https://support.hp.com/us-en/drivers/selfservice/hp-pavilion-g7-2200-notebook-pc-series/5296086/model/5333368
* Firmware release date (if available on OEM website)
https://support.hp.com/us-en/drivers/selfservice/hp-pavilion-g7-2200-notebook-pc-series/5296086/model/5333368

* Link to the device page on LVFS.
https://support.hp.com/us-en/drivers/selfservice/hp-pavilion-g7-2200-notebook-pc-series/5296086/model/5333368

**Comment by hughsie** [comment]
HP only have one laptop on the LVFS, so I think it's worthwhile contacting them and asking for more models to be supported.

**Comment by FireWolf74** [comment]
Ok here is a question how do we go about asking them???
Or is this something that LVFS has to do?

**Comment by superm1** [comment]
So this section of labels for missing firmware is supposed to be for devices already on LVFS but missing a firmware update.  Since this device isn't yet on LVFS, I'm going to close this issue.  You'll need to contact the manufacturer to request them to add the device to LVFS.
