### ISSUE TITLE
GNOME-Software

### ISSUE THREAD

**Issue by FireWolf74** [hughsie/lvfs-website#121]
I just looked in my gnome-software under hardware this was all I see.
![screenshot from 2018-06-13 12-59-28](https://user-images.githubusercontent.com/33334258/41379146-3c90dda4-6f2f-11e8-8581-e7486632596e.png)
I don't see HDD, video graphic for AMD, or even updates to the trackpad or many other components that I have on my system.
Is that not an issue?
Also I have tried to see what version of fwupd I have to no luck in see it.

**Comment by superm1** [comment]
This issue is filed in the wrong place.  It should be filed here:
https://gitlab.gnome.org/GNOME/gnome-software
