### ISSUE TITLE
Composite firmware uploads are rejected unless all components change

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#122]
This is with `/lvfs/firmware/650`. I found that if only one of the components changed the upload is rejected saying that there already is a firmware that has the same version for one of the other components.

At least for this device it's quite unlikely that all the components will move at the same time, so I think that composite firmware CAB files need to cover this scenario.

**Comment by superm1** [comment]
If you need the CAB file as it was built to reproduce this error (or event just the metainfo files from it) happy to send it.

**Comment by hughsie** [comment]
It would be useful to have the .cab pls.

**Comment by superm1** [comment]
Sent it over email.

**Comment by hughsie** [comment]
^this fixes the issue for me, but it does depend on https://github.com/hughsie/lvfs-website/pull/120 as we have to show the versions for the components to make any kind of sense.
