### ISSUE TITLE
8bitdo SF30/SN30 New Firmware

### ISSUE THREAD

**Issue by kylehawes** [hughsie/lvfs-website#123]
For missing firmware please provide the following items:

* Link to firmware update at OEM website
http://download.8bitdo.com/Firmware/Controller/SN30pro+SF30pro/SN30pro+SF30pro_Firmware_V1.26.zip

* Firmware release date (if available on OEM website)
2018-05-19

* Link to the device page on LVFS.
https://fwupd.org/lvfs/device/b3850dd5-a010-5d5c-8834-2ff809e95869

**Comment by hughsie** [comment]
I've uploaded this to the LVFS and put it in the testing channel. It will be available in about 30 minutes. Can you enable the testing repo and tell me if the firmware update works please.

**Comment by kylehawes** [comment]
I tried updating and ran into this same issue: https://github.com/hughsie/fwupd/issues/565 so I added a comment there. Let me know if I can provide any more info.
