### ISSUE TITLE
Failing to create new accounts for Dell account

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#136]
I was trying to add two people a few minutes ago and encountered these two messages when trying to add them.

`Failed to add user: Admin has not set the account policy for this vendor`
`Failed to add user: Email address does not match account policy`

I tried `@DELL.com`, `@dell.com`, `@Dell.com` but none of them seemed to work for creating the account.

**Comment by hughsie** [comment]
The account policy was never setup as dell was using oauth. I've added a *@dell.com glob now, it's case insensitive.

**Comment by superm1** [comment]
perfect thanks.  Yeah it's for creating accounts that will be used with OAuth but need to be created initially to set the permissions right before they would log in the first time with OAuth.

Just confirmed it worked now.
