### ISSUE TITLE
Unable to visit https://fwupd.org/lvfs/firmware/718 and https://fwupd.org/lvfs/firmware/719

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#140]
I noticed after these were uploaded they could no longer be viewed.

**Comment by hughsie** [comment]
My error, sorry. The custom.cfg wasn't overwritten when I deployed, so the salts were missing. Seems to work now.

**Comment by superm1** [comment]
Thanks, yes seems to be working.
