### ISSUE TITLE
Potentially allow an overwrite action on upload

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#143]
I'm exploring with a team the option to have LVFS connected to some build server automation.  Builds released to customers will always have increasing version numbers.  For internal development purpose however its not uncommon multiple builds with the same version number.  Once they're released to a wider audience than the will be incremented for the next build.

For example there might be 10 builds that are "candidate" builds for the `1.0.0` firmware that a product may launch with.

So because of this I'm wondering what you would think about a hidden checkbox as part of the upload POST that would allow overwrite (if in embargo channel).  That overwrite would actually perform like a delete and then upload the new one.

**Comment by hughsie** [comment]
Wouldn't it be better to just 'delete' the previous firmware from the automated script? We could provide API to get the firmware_id from the firmware checksum or GUID+version. I'm hesitant to encode too much magic into the upload process. Perhaps a semi-hidden `replace()` method might be a better compromise.

**Comment by superm1** [comment]
The problem so far has been being able to get `firmware_id` to know what to delete in advance, so an API to get that would work too.  The slight problem with getting the firmware ID from the checksum or GUID is that there might be a bunch of different payloads in the cab so it's going to be unclear which one is the one that LVFS pivots from.  I think it's usually the first alphabetically but then that's hidden magic too.

That's why I was thinking `overwrite/replace` makes sense.
