### ISSUE TITLE
Liberapay is in trouble

### ISSUE THREAD

**Issue by his10** [hughsie/lvfs-website#149]
In case you're not aware of it, you should withdraw your income from your Liberapay wallet as soon as possible: https://medium.com/liberapay-blog/liberapay-is-in-trouble-b58b40714d82

You do not want to ignore this: https://github.com/liberapay/liberapay.com/pull/1169#issuecomment-404459576

**Comment by hughsie** [comment]
Done, thanks for letting me know, much appreciated.
