### ISSUE TITLE
Documentation for BT OEMs to easily understand fwupd/LVFS

### ISSUE THREAD

**Issue by ford-prefect** [hughsie/lvfs-website#15]
It would be good to have something that we could send to OEMs of Bluetooth devices to explain what the service is all about, and what would be involved for them to participate.

I'm thinking something along the lines of what [Richard's post about  CSR dfu](https://blogs.gnome.org/hughsie/2017/12/11/csr-devices-now-supported-in-fwupd/) covers, but more geared towards vendors who are not aware of anything Linux related (including the reach this effort has).

**Comment by hughsie** [comment]
Before I start on this, do have a list of vendor contacts I would sent this to? I don't want to spend a couple of days on a document nobody is going to read! :)

**Comment by ford-prefect** [comment]
Sorry, I've not had enough bandwidth to follow up on this now. Will reopen
if I do again.
