### ISSUE TITLE
Feature request: Boot image support (Lenovo and others?)

### ISSUE THREAD

**Issue by alaraun** [hughsie/lvfs-website#157]
Add support for custom boot images
- add boot image
- remove boot image
- keep boot image on upgrade

Justification
Many organizations use boot images to idendify their hardware

Current  status
After firmware upgrade for Lenovo T460s custom boot image will be removed
https://fwupd.org/lvfs/device/42f29620-3d63-4f09-950b-9b7055570f28

**Comment by hughsie** [comment]
Do you have any links on how to add a custom boot image? Ideally with a UEFI capsule example -- thanks.

**Comment by alaraun** [comment]
Unfortunately not. Until now we have used Windows based upgrades.

**Comment by hughsie** [comment]
I've asked my Lenovo contact by email just now for a solution.

**Comment by superm1** [comment]
What does custom boot image mean?  Like keeping UEFI NVRAM boot variables across a capsule upgrade?

**Comment by hughsie** [comment]
Nah, like a .BMP image that changes the OEM startup logo to something else.

**Comment by superm1** [comment]
Oh okay.

**Comment by superm1** [comment]
I realize I've seen this in two places, this is a duplicate of https://github.com/hughsie/fwupd/issues/906
