### ISSUE TITLE
Thinkpad L570 bricking on update

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#163]
Saw this reported: https://bugs.launchpad.net/bugs/1791407

I think that firmware should be pulled back to testing.

**Comment by superm1** [comment]
FYI 3 more reports came in on this..

**Comment by hughsie** [comment]
Ohh shit. Where are the other 3 reports out of interest?

**Comment by superm1** [comment]
I marked the duplicate so they link back to that Launchpad bug.
https://bugs.launchpad.net/ubuntu/+source/fwupdate/+bug/1791589

It's marked as "affecting 3 people", so that means there should be 4 distinct people this has happened to now.

**Comment by hughsie** [comment]
I've pulled it from stable, the LVFS should resign in a few minutes. I've sent an email to my Lenovo contact about this just now.

**Comment by hughsie** [comment]
I'm still waiting back from Lenovo, but I'll close this as there's probably nothing public they can add here anyway. I'll continue on that launchpad ticket. Thanks for keeping an eye on that and opening this issue.
