### ISSUE TITLE
[missing firmware] Dell OptiPlex 3040

### ISSUE THREAD

**Issue by olifre** [hughsie/lvfs-website#164]
For missing firmware please provide the following items:

* Link to firmware update at OEM website
  https://www.dell.com/support/home/de/de/debsdt1/drivers/driversdetails?driverId=YMKWH

* Firmware release date (if available on OEM website)
  21.06.2018

* Link to the device page on LVFS.
  Supposedly https://fwupd.org/lvfs/device/d63450d6-d611-48ac-8f3b-8d29bad80248 , but it reads OptiPlex 3046?

**Comment by olifre** [comment]
On a side-note, on the machine, I get:
```
# fwupdmgr get-devices
OptiPlex 3040 System Firmware
  DeviceId:             8330a096d9f1af8567c7374cb8403e1ce9cf3163
```

**Comment by superm1** [comment]
Two separate problems here.
1. Missing firmware.  I'll ping right folks regarding that.
2. Wrong device showing up in LVFS description.  @hughsie It seems like 3040 and 3046 description are getting merged.

**Comment by hughsie** [comment]
@superm1 is this fixed now?

**Comment by superm1** [comment]
Looks fixed to me now.
