### ISSUE TITLE
perma-delete item

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#166]
Can you permanently remove item 1017?   The first component changed in 1035 and I don't want 1017 to cause confusion.

**Comment by hughsie** [comment]
Do you mean delete the .cab file, or nuke the database entry entirely? I've not got any UI to do either, so I guess it's a good time to add it.

**Comment by superm1** [comment]
Nuke the database entry entirely.  The CAB isn't useful either anymore, but the database entry going is the important part.

**Comment by hughsie** [comment]
(i'll deploy this on Sunday)

**Comment by superm1** [comment]
I guess don't forget to actually nuke the database entry when you deploy too then :)

**Comment by hughsie** [comment]
1017 nuked.

**Comment by superm1** [comment]
Looks like now that that's nuked the old one with the same name is still showing up. (990).

Also I notice something that seems off with that entry..


```

The deleted metadata will be signed in 14 minutes. | Undelete
-- | --
```

**Comment by hughsie** [comment]
> Looks like now that that's nuked the old one with the same name is still showing up. (990).

You want me to nuke 990 too?

> The deleted metadata will be signed in 14 minutes

Ha! That's going to be waiting a while, as the deleted remote isn't on cron job. I can look at this tmw.

**Comment by superm1** [comment]
>You want me to nuke 990 too?

990, 970, 923

I think that should get rid of all the old entries.

**Comment by hughsie** [comment]
> 990, 970, 923

All nuked.
