### ISSUE TITLE
Dell XPS 15 9570: annoying fan noise after recent firmware update

### ISSUE THREAD

**Issue by grulja** [hughsie/lvfs-website#170]
Hi,

two days ago I updated latest firmware in my laptop, the latest version is now 1.5.0 and the update was successfuly installed. With the new firmware I have annyoing fan noise, which wasn't present before and I can hear it even when the laptop is not under heavy load. If I run some heavier tasks, like compilation, it gets worse and the fan noise is super annoying. It might be just a coincidence that the fan started making this noise after the firmware update and it just need replacement, because I saw similar reports mentioned by users before the update. This problem was even recorded on YouTube by someone a month ago and I have the exact problem.

Latest firmware: https://fwupd.org/lvfs/device/e4d7bdc4-cc95-4aa0-a982-5e915fc04bf0
Youtube video: https://www.youtube.com/watch?v=VthJEyOTXIo

**Comment by superm1** [comment]
Please report this in the Dell forums and the social media team will be monitoring in that area.  This issue bucket is mostly intended for missing firmware items.
