### ISSUE TITLE
Missing firmware for Delle latitude E7240

### ISSUE THREAD

**Issue by vs1960** [hughsie/lvfs-website#173]
For missing firmware please provide the following items:

https://www.dell.com/support/home/no/no/nodhs1/product-support/product/latitude-e7240-ultrabook/drivers

* Firmware release date (if available on OEM website)

* Link to the device page on LVFS.

**Comment by superm1** [comment]
This area isn't for requesting new platform support, it's specifically for platforms that are on LVFS but missing a firmware upload.
