### ISSUE TITLE
Dell OptiPlex 7040 firmware needs to be updated

### ISSUE THREAD

**Issue by meeldrid** [hughsie/lvfs-website#18]
Version 1.5.7 is latest at fwupd.org and version 1.8.1 is available from Dell's support site.

For missing firmware please provide the following items:

* Link to firmware update at OEM website
http://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverId=KTMMD
* Firmware release date (if available on OEM website)
04 Jan 2018
* Link to the device page on LVFS.
https://fwupd.org/lvfs/device/b950d63c-f9a5-4823-b48d-395e960ab468

**Comment by superm1** [comment]
It's there now, thanks for reporting
