### ISSUE TITLE
[missing firmware] Lenovo T450s

### ISSUE THREAD

**Issue by maztaim** [hughsie/lvfs-website#181]
For missing firmware please provide the following items:

* Link to firmware update at OEM website
https://pcsupport.lenovo.com/us/en/products/LAPTOPS-AND-NETBOOKS/THINKPAD-T-SERIES-LAPTOPS/THINKPAD-T450S/downloads/DS102110

* Firmware release date (if available on OEM website)
1-Oct-2018

* Link to the device page on LVFS.
Not one yet :)

It's a stretch on my part.  I know it's an older laptop, but it checks out and I use it regularly.  They update the firmware still(ish).  I would LOVE to not do the eltorito and dd shuffle.

**Comment by hughsie** [comment]
I can certainly ask Lenovo, but I think they're concentrating on the newer hardware at the moment.

**Comment by maztaim** [comment]
Like I said, it's a stretch.  Don't sweat it if they don't want to.  I'll catch it on the next laptop.

**Comment by maztaim** [comment]
I don't know if you want to put a time-limit on IF they are going to do it, but whenever you feel comfortable, close this out.  I like clean issue lists and I certainly don't want to fill up yours.

**Comment by maztaim** [comment]
Nevermind.  I didn't know I could close it.  Thanks for checking.
