### ISSUE TITLE
Dell XPS 9365 firmware update missing

### ISSUE THREAD

**Issue by ausil** [hughsie/lvfs-website#189]
For missing firmware please provide the following items:
There is a previous version 1.5.1 missing also

* Link to firmware update at OEM website
https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverId=THDDP&osCode=BIOSA&productCode=xps-13-9365-2-in-1-laptop
* Firmware release date (if available on OEM website)
26 Oct 2018
* Link to the device page on LVFS.
https://fwupd.org/lvfs/device/d636245a-c31b-4454-b9a5-9893c6e6f6cc

**Comment by ausil** [comment]
https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverId=570MM&osCode=BIOSA&productCode=xps-13-9365-2-in-1-laptop there is another update to 2.3.1 that is not available

**Comment by hughsie** [comment]
@superm1 ?

**Comment by superm1** [comment]
I've pinged someone internal on this.

**Comment by superm1** [comment]
2.3.1 is now there.
