### ISSUE TITLE
Allow zipfile upload

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#20]
Like LVFS Microsoft requires _.CAB file_ to upload to [Windows Hardware Dev Center](https://developer.microsoft.com/en-us/windows/hardware/dashboard-sign-in).

However after the content is signed by Microsoft, it's unavailable in .CAB format from Hardware Dev Center.  It's instead distributed using _.ZIP file_.

Since LVFS is going to repackage into a CAB format anyway for distribution, I think it makes sense to allow LVFS to accept the ZIP file format and repack it into CAB.

This will make it easier to re-use content otherwise headed to Windows Update.

**Comment by hughsie** [comment]
Makes sense to me I guess, although I think it does muddy the "message" about what the LVFS does. Maybe we can just accept .zip files without making a big song-and-dance about it in the documentation? Could you also upload a .zip file somewhere for testing please, as I know there are many types of "zip file" in the wild.

**Comment by superm1** [comment]
That's fine to me.

Yep, here's an example: https://dell.box.com/s/3nk46cbfz44itq4qg9b8apmoo8b8gyqy
I tried to "upload" so you can get something in LVFS log about what it saw from that file too.

Associated error on my side was: "Internal error: Invalid file type: Failed to extract: /tmp/cabarchive_oywQKv.cab: no valid cabinets found"

**Comment by hughsie** [comment]
The zip files have got a path, is that expected? Is that unavoidable?

**Comment by superm1** [comment]
It's unavoidable but it can be ignored.

**Comment by hughsie** [comment]
> It's unavoidable but it can be ignored

It's not even a standard zip file, the backslashes are `\\` -- i'll have to special case it.

**Comment by superm1** [comment]
Just to confirm you restarted the lvfs instance right? I haven't checked, just wanted to ask before having folks upload.

**Comment by hughsie** [comment]
On 15 January 2018 at 02:50, Mario Limonciello <notifications@github.com> wrote:
> Just to confirm you restarted the lvfs instance right? I haven't checked, just wanted to ask before having folks upload.

I've not restarted it yet; I can do this later this afternoon if you
need it right away. I was trying to limit the reboots of the LVFS to
just Sunday mornings going forward, but I guess we need some kind of
way of knowing what git version is currently deployed.

Richard

**Comment by superm1** [comment]
Yeah if you can that would be great.  We're intending to adjust so that's what we upload from.

**Comment by hughsie** [comment]
Okay, should be live now. Yell if you have any problems.
