### ISSUE TITLE
Visiting affiliations errors out

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#210]
I try to visit this:
https://fwupd.org/lvfs/vendor/13/affiliations

And it errors.
`The LVFS is temporarily unavailable and should be back soon.`

**Comment by hughsie** [comment]
Hmm, works for me, so must be a !admin thing. I'll take a look in the logs.

**Comment by hughsie** [comment]
Fixed in https://github.com/hughsie/lvfs-website/commit/9929389ab96cf553ab9c045a3f82a10ec31a4ad1 -- which I've just deployed. Can you verify please? Thanks.

**Comment by superm1** [comment]
Yep looks good.
