### ISSUE TITLE
Really delete firmware after 6 months

### ISSUE THREAD

**Issue by hughsie** [hughsie/lvfs-website#215]
We're not low on space yet, but the LVFS is growing every month from a storage requirement and backup point of view. We store more firmware in the deleted state than any other repo! Would it be expected that firmware that's been in the deleted state to be removed after say 6 months? Or just not backed up? I'm not sure if we just want to remove the .cab file itself, or all database entries as well. Maybe storage is cheap, and I just need to provision some more space. Ideas welcome.

**Comment by superm1** [comment]
I think a warning that firmware in the deleted state will be removed after some period of time is shown that seems perfectly fine to me.
