### ISSUE TITLE
Missing Firmware update: 8bitdo NES30 v4.10

### ISSUE THREAD

**Issue by plafue** [hughsie/lvfs-website#216]
For missing firmware please provide the following items:

* Link to firmware update at OEM website
  http://download.8bitdo.com/Firmware/Controller/N30+F30/N30+F30_Firmware_V4.10.zip

* Firmware release date (if available on OEM website)
  2018-03-07

* Link to the device page on LVFS.
  https://fwupd.org/lvfs/component/289/all

**Comment by hughsie** [comment]
Is the N30 device the same as the NES30 device? What's the VID and PID of the device please?

**Comment by plafue** [comment]
Yes, it is - sorry for the confusion (The back of my controller says NES30 but it's exactly the same model). `lsusb` says `2dc8:ab12`.
![img_20181217_130451](https://user-images.githubusercontent.com/1915763/50086373-1f00a380-01fd-11e9-8da2-ce74068f4ebb.jpg)

**Comment by plafue** [comment]
Thanks for the quick response!

**Comment by hughsie** [comment]
Does https://fwupd.org/downloads/2999ee63c0cff96893c1614955f505cb4f0fa406-8Bitdo-SFC30_NES30_SFC30_SNES30-4.10.cab work for you?

**Comment by plafue** [comment]
```
≻  fwupdmgr install ~/Downloads/2999ee63c0cff96893c1614955f505cb4f0fa406-8Bitdo-SFC30_NES30_SFC30_SNES30-4.10.cab
Decompressing…         [***************************************]
Specified firmware is older than installed '4.10 < 4,01'
```

**Comment by hughsie** [comment]
> 4.10 < 4,01

A comma?! Can you try running fwupdmgr with LANG=C please? Thanks.

**Comment by plafue** [comment]
```bash
[10:12] ~ 
≻  env | grep LANG             
LANG=C
[10:12] ~ 
≻  env | grep LC               
LC_ADDRESS=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
[10:12] ~ 
≻  fwupdmgr install ~/Downloads/2999ee63c0cff96893c1614955f505cb4f0fa406-8Bitdo-SFC30_NES30_SFC30_SNES30-4.10.cab
Decompressing…         [***************************************]
Specified firmware is older than installed '4.10 < 4,01'
```

:man_shrugging: Upgrading from older firmware to 4.01 worked flawlessly. Sorry for the inconvenience and thanks for your support!

**Comment by hughsie** [comment]
Is there any way the fwupd daemon could be running in a European locale? The ebitdo plugin does this:

    tmp = g_strdup_printf ("%.2f", version / 100.f);
    fu_device_set_version (FU_DEVICE (self), tmp);

**Comment by plafue** [comment]
It could very well be, i'll stop it and start it manually and will get back to you. If you don't mind me asking: why should a version number be affected by the user's locale?

**Comment by plafue** [comment]
here is some output from `service fwupd status` which could be of interest:

```
fwupd[10655]: Destination Address: 800a000
fwupd[10655]: Destination Length:  45568
fwupd[10655]: new device version '4,01' was is not '4.01', fixing up
```

**Comment by hughsie** [comment]
> why should a version number be affected by the user's locale

Some locales (e.g. fr_FR) would display 1 and a half as `1,5` and 20 thousand as `20.000`

**Comment by plafue** [comment]
> Some locales (e.g. fr_FR) would display 1 and a half as 1,5 and 20 thousand as 20.000

I'm aware of that fact, but i was wondering why should a version number be affected by the decimal symbol of a locale, and not always use a dot as a separator.

**Comment by plafue** [comment]
Starting the deamon with `LANG=C` did the trick. Pairing with a computer and reading input events worked flawlessly after the update. Thank you for your patience!

**Comment by hughsie** [comment]
I've pushed this to stable now -- if you see any other firmware on the LVFS for 8bitdo products please let me know. I'll submit a PR for the locale gotcha in a few minutes.

**Comment by plafue** [comment]
That's great, thank you very much!
