### ISSUE TITLE
Links to vendors websites and direct access to vendorlist subpage

### ISSUE THREAD

**Issue by pietrushnic** [hughsie/lvfs-website#217]
It would be great to have 2 improvements related to [vendorlist website](https://fwupd.org/vendorlist):

1. I can't see direct access from main or manu website to vendorlist. What I do is `menu->Supported Devices->vendor engagement list`, what IMO is little bit convoluted. There are of course links on other subpages to vendorlist, but it still not so direct.
2. It would be great to have link to vendor website. For example in my case 3mdeb is registered as ODM, but what we can do is integration of LVFS/fwupd in firmware for various devices. I see similar companies on list. It would be great of if someone interested in that could just click the link and get to place when support can be obtained. Right now it requires additional search engine call.

**Comment by hughsie** [comment]
For the first issue, what would the header entry be? Something like `Existing Vendors` or a more abstract `Who uses the LVFS` or `Vendor Status`

As for a link, that's a good idea. Would we just hyperlink the existing vendor name, or have some kind of subtitle for that? e.g. we could have a `More information` or `Info` button on the very right hand side which takes you to the vendor.

**Comment by pietrushnic** [comment]
@hughsie I think all propositions address my issue, so it is up to you and way you build UX for people interested.

**Comment by pietrushnic** [comment]
:+1:
