### ISSUE TITLE
Dell Precision 3630 unsupported

### ISSUE THREAD

**Issue by paulmenzel** [hughsie/lvfs-website#223]
Could Dell please upload the necessary files for the Dell Precision 3630? It’s a new model, and in the firmware there is an option for UEFI Capsule support, so only the files on LVFS are missing. This is a step backwards from Dell, especially, as they also offer it with Ubuntu. I really just assumed that Dell would continue supporting LVFS/fwupd with all their new models.

**Comment by superm1** [comment]
Thanks for notifying, I'll reach out to the team that manages that system.

**Comment by superm1** [comment]
I've gotten confirmation it's here now.
https://fwupd.org/lvfs/device/c0745fac-f5a5-46c9-b716-3cc5781e876e

Sorry for the delay in that getting uploaded.  If you see something else missing feel free to raise another issue.

**Comment by paulmenzel** [comment]
Am 14.01.19 um 23:21 schrieb Mario Limonciello:
> I've gotten confirmation it's here now. 
> https://fwupd.org/lvfs/device/c0745fac-f5a5-46c9-b716-3cc5781e876e
> 
> Sorry for the delay in that getting uploaded.  If you see something
> else missing feel free to raise another issue.

Thank you very much for taking care of that.  It’s much appreciated.
