### ISSUE TITLE
Unpack the firmware at upload and look for problems

### ISSUE THREAD

**Issue by hughsie** [hughsie/lvfs-website#227]
We can add a `Problem` if the EFI binary is either unsigned, or if it has no capsule header. In the future we could do other chipsec-style tests, although probably out of scope for this bugreport.

**Comment by superm1** [comment]
I think no capsule header is pretty easy to check for, but how do you handle checking for signature generically?

**Comment by hughsie** [comment]
> how do you handle checking for signature generically

We'll hopefully have somebody working on this exact problem in the next year or so. I think it might be enlightening to find out _who_ is signing the various vendor binaries.
