### ISSUE TITLE
Missing Firmware - Dell Latitude 5x80 (BIOS 1.13.0)

### ISSUE THREAD

**Issue by Rokin05** [hughsie/lvfs-website#235]
For missing firmware please provide the following items:

* Link to firmware update at OEM website
https://downloads.dell.com/FOLDER05358851M/1/Latitude_5X80_Precision_3520_1.13.0.exe
https://downloads.dell.com/FOLDER05358852M/1/Latitude_5X80_Precision_3520_1.13.0.txt

* Firmware release date (if available on OEM website)
Version 1.13.0 - 11 déc. 2018

* Link to the device page on LVFS.
https://fwupd.org/lvfs/device/49e03513-7afe-498a-9d03-89e5ba1da865

* Note: fixes this issue

> Fixes
> - Fixed the issue that occurs in the system setup (BIOS) where the system stops responding when hot swapping a Dell dock that has an external monitor plugged in.
> - Fixed the issue where the Dell WD15 dock loses connection when connected instantly after Dell TB16 dock is unplugged.
> - Fixed the issue where the system does not resume from sleep after you undock it from either a Dell WD15 or Dell TB16 docking station with USB power share enabled.
> 
> Enhancements
> - Enhanced Wake on Lan to PXE (Preboot Execution Environment) feature on DELL WD15 and TB16 dock.
> - Updated Embedded Controller Engine firmware.
> - Updated Thermal Algorithm for performance.

Thank you !

**Comment by superm1** [comment]
It's available here now.  Feel free to raise another issue if you see another one missing.
https://fwupd.org/lvfs/device/49e03513-7afe-498a-9d03-89e5ba1da865
https://fwupd.org/lvfs/device/8b7b32a7-0dee-4851-9707-ee7e8c2c4881
