### ISSUE TITLE
Firmware is missing Dell inspiron 5423 

### ISSUE THREAD

**Issue by judd1** [hughsie/lvfs-website#237]
For missing firmware please provide the following items:

* Link to firmware update at OEM website

https://downloads.dell.com/FOLDER05002016M/1/5423A16.EXE → Last update

* Firmware release date (if available on OEM website)

https://www.dell.com/support/Home/ar/es/ardhs1/Drivers/DriversDetails?driverId=Y8YTR

* Link to the device page on LVFS.

https://fwupd.org/lvfs/search?value=inspiron+5423

https://www.dell.com/support/home/ar/es/ardhs1/product-support/servicetag/8cgcqt1/drivers

 efi: EFI v2.31 by American Megatrends
 efi:  ACPI=0xc8d1f000  ACPI 2.0=0xc8d1f000  SMBIOS=0xca4b0398 
 SMBIOS 2.7 present.
 DMI: Dell Inc. Inspiron 5423/0H4MCJ, BIOS A08 11/26/2012 → Current firmware.

--
I never had problems with the current firmware: BIOS A08 11/26/2012 with no Linux distro, right now; is too much time has passed ... and with the new kernels that will come (current 4.20.1), it seems to me that I have to update Bios or am I wrong?

**Comment by superm1** [comment]
This system isn't supported by LVFS.

**Comment by judd1** [comment]
Also, thank you very much for your time!

**Comment by judd1** [comment]
Also, thank you very much for your time!
