### ISSUE TITLE
Make vendor page more interesting

### ISSUE THREAD

**Issue by hughsie** [hughsie/lvfs-website#248]
At the moment it's pretty dull and looks like it's from the '90s. I'm thinking something like this:

![screenshot from 2019-01-25 17-00-08](https://user-images.githubusercontent.com/151380/51760653-cdccb500-20c2-11e9-9c12-a8a58a547115.png)

@superm1 Comments and other ideas very welcome.

**Comment by superm1** [comment]
The asymmetrical look of the 3 columns caused by some vendors having more information than others I personally don't like.  Might be better to have a UX guy look this over if the goal is an overhaul that's modern.

Call me boring, but I like regular tables to find information 😄

**Comment by superm1** [comment]
Something I do think that would "might" be useful on this page is an "RSS" style list of uploads recently promoted to testing or stable.  Similar to what's on https://fwupd.org/lvfs/devicelist for "new" devices but showing uploads.

**Comment by hughsie** [comment]
Ya, I'm not sold yet. I'll polish up the existing table and make some of the underlying model changes first. Thanks.
