### ISSUE TITLE
app.wsgi throws with missing namespace in gi package

### ISSUE THREAD

**Issue by istanev93** [hughsie/lvfs-website#252]
Trying to run the website from a Ubuntu 16.04. Attempted with both python2.7 and python3.5, but I'm facing the problem with both. At some point, after installing all the necessary packages via pip/pip3, I get the error below (see stack trace).

I can't seem to resolve it in any way, I have pygobject installed, as well as gi. A Google search doesn't bring up anything related.

```python
Traceback (most recent call last):
  File "./app.wsgi", line 7, in <module>
    from app import app as application
  File "/home/bemadmin/lvfs-website/app/__init__.py", line 20, in <module>
    from .pluginloader import Pluginloader
  File "/home/bemadmin/lvfs-website/app/pluginloader.py", line 14, in <module>
    from .util import _event_log
  File "/home/bemadmin/lvfs-website/app/util.py", line 24, in <module>
    gi.require_version('GCab', '1.0')
  File "/home/bemadmin/.local/lib/python3.5/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GCab not available
```

**Comment by istanev93** [comment]
I managed to fix this with the following installs, which should probably be included somewhere in the documentation...

```sudo apt install -y python3-pip libcairo2-dev libgirepository1.0-dev python3-gi python3-gi-cairo python-gobject python-gi-dev gob2 python-gi-cairo pkg-config libcairo2-dev gcc python3-dev gcab gir1.2-libgcab-1.0 libgcab-1.0-0 libgcab-dev libglib2.0-dev appstream appstream-util gir1.2-appstream gir1.2-appstreamglib-1.0 libappstream-dev libappstream-glib-dev libappstream-glib8 libappstream3 libappstream4 python3-mysqldb python-mysqldb

pip3 install sqlalchemy flask flask_login flask_migrate flask_mail flask_oauthlib lxml pycairo pygobject gobject PyGObject humanize onetimepass pyqrcode
```

**Comment by hughsie** [comment]
Didn't `pip2 install -r requirements.txt` work? If you want to use python3, you need to use the untested wip/hughsie/python3 branch.

**Comment by istanev93** [comment]
Unfortunately not, I get a different error (see below). And when I manage to install gi and all the other requirements, I end up at the namespace error in the original issue.

```python
Traceback (most recent call last):
  File "./app.wsgi", line 7, in <module>
    from app import app as application
  File "/home/bemadmin/lvfs-website/app/__init__.py", line 20, in <module>
    from .pluginloader import Pluginloader
  File "/home/bemadmin/lvfs-website/app/pluginloader.py", line 14, in <module>
    from .util import _event_log
  File "/home/bemadmin/lvfs-website/app/util.py", line 23, in <module>
    import gi
ImportError: No module named gi
```

**Comment by hughsie** [comment]
You need to install the python2-gobject or python34-gobject system wide package. I don't think you can do that using pip.

**Comment by istanev93** [comment]
That's correct. I tried the same thing with pip2 but after installing python-gobject I end up in the situation in my first post:
`ValueError: Namespace GCab not available`
There's a bunch of extra packages that must be installed on the system. I threw everything in the sink that I could find by Googling around until I made it work. I find that any of the following packages fix the problem...
```
sudo apt install -y python-pip libcairo2-dev libgirepository1.0-dev python-gi python-gi-cairo python-gobject python-gi-dev gob2 pkg-config libcairo2-dev gcc gcab gir1.2-libgcab-1.0 libgcab-1.0-0 libgcab-dev libglib2.0-dev appstream appstream-util gir1.2-appstream gir1.2-appstreamglib-1.0 libappstream-dev libappstream-glib-dev libappstream-glib8 libappstream3 libappstream4 python-mysqldb libmysqlclient-dev
```

**Comment by hughsie** [comment]
> gir1.2-libgcab-1.0

...this is the one you wanted.

**Comment by hughsie** [comment]
That'd be useful to add to the README.md if you're offering :)

**Comment by istanev93** [comment]
Feel free to add it, hopefully it helps others facing the same issue! Alternatively, I can submit a PR request some time soon
