### ISSUE TITLE
Database installation errors: VARCHAR requires a length on dialect mysql

### ISSUE THREAD

**Issue by istanev93** [hughsie/lvfs-website#253]
Hello,

I'm running the installation commands from the README to set up the database for LVFS, but I'm getting a CompileError. I had to modify the command to _flask_ instead of _flask-2_:
```shell
FLASK_APP=app/__init__.py flask initdb
```
I get the following error (omitted a lot of the stack trace refers only to python2.7 packages):
```python
bemadmin@lin1604lvfs:~/lvfs-website$ FLASK_APP=app/__init__.py flask initdb
/home/bemadmin/.local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "/home/bemadmin/.local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/bemadmin/.local/lib/python2.7/site-packages/flask_cli/cli.py", line 502, in main
    cli.main(args=args, prog_name=name)
...
...
  File "/home/bemadmin/lvfs-website/app/dbutils.py", line 186, in init_db
    db.metadata.create_all(bind=db.engine)
  File "/home/bemadmin/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 4200, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
...
...
  File "/home/bemadmin/.local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 3295, in visit_unicode
    return self.visit_VARCHAR(type_, **kw)
  File "/home/bemadmin/.local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 1880, in visit_VARCHAR
    "VARCHAR requires a length on dialect %s" % self.dialect.name
sqlalchemy.exc.CompileError: (in table 'agreements', column 'text'): VARCHAR requires a length on dialect mysql
```

Running on Ubuntu 16.04. Have I missed some important step before trying to run this?

**Comment by hughsie** [comment]
> Have I missed some important step before trying to run this

No, but you might be the 3rd person in the world to try to set this up :) If you change all the `Unicode` types in app/model.py to `Text` that will probably unstick the database creation.

**Comment by istanev93** [comment]
That seems to work, thank you! I got an additional error after that:
`sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1170, "BLOB/TEXT column 'group_id' used in key specification without a key length") [SQL: u'CREATE INDEX ix_vendors_group_id ON vendors (group_id)'] (Background on this error at: http://sqlalche.me/e/e3q8)`
This one I was able to resolve by changing `app/models.py`'s Vendor group_id from `Text` to `String(200)`, so initdb ran successfully.

I wasn't able to run `FLASK_APP=app/__init__.py flask modifydb` but it seems like the LVFS server is now serving index.html without it, so I guess that step is not needed?

**Comment by hughsie** [comment]
I've spent a bit of time this evening testing, and then fixing the various issues. I'll close this bug, but please re-open if you find anything else crazy in the wip/hughsie/python3 branch. We're merging that branch to master tomorrow, so there's no point testing the python2 things. Thanks.
