### ISSUE TITLE
Firmware $NAME dropped a GUID previously supported 701fd626-1d90-5e6f-9b1d-ca29f21c47a2

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#254]
I noticed this failure from an automation upload this morning and can reproduce it with a manual upload.

it's intentional that the GUID that got dropped should get dropped.  It won't happen again, but did have to happen that once.
Just not sure how to recover though.  Do all the "older" releases need to be manually deleted?

**Comment by superm1** [comment]
Yeah I just double checked; the automatic upload was done by a user with `local+locked robot`.

**Comment by hughsie** [comment]
Hmm, yes. PR coming up...

**Comment by hughsie** [comment]
Gahh, I did want to do a PR but pushed the wrong branch. Can you check that commit makes sense and if not I'll revert and try again.

**Comment by superm1** [comment]
That's probably sensible to have QA user be allowed to fix it.

I guess the question I'll have is whether that's a "permanent" fix.  Eg since there are still CAB files with the "missing" GUID in the remote will it flag again?

**Comment by hughsie** [comment]
> will it flag again

I don't think so; I think this test is only done at upload time.

**Comment by superm1** [comment]
OK, I guess can you restart the instance and i'll try again and then keep an eye out in the next automatic one.

**Comment by hughsie** [comment]
Done.

**Comment by superm1** [comment]
Thanks, it was able to upload from my account.  I'll monitor what happens on the next robot upload (which might be a week or two from now).

**Comment by superm1** [comment]
The robot ran again today It looks like the robot upload is still flagging this.
```

✪ Firmware would drop a GUID previously supported: 701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2,701fd626-1d90-5e6f-9b1d-ca29f21c47a2
--
```

Should I manually remove the "old" payloads to try to help?

**Comment by hughsie** [comment]
Okay, two bug there :) I'll have a look now.

**Comment by hughsie** [comment]
What about something like this?

         if dropped_guids:
    -        if g.user.is_qa:
    +        if g.user.is_qa or g.user.is_robot:

**Comment by superm1** [comment]
Well other than it logging the message for eternity but letting it go that would _fix the problem_.

**Comment by hughsie** [comment]
I'm also wondering if it makes sense to move the "dropped guid" functionality out to a "test" that can be waived. The least I do in views_upload.py the better.

**Comment by superm1** [comment]
Has this been deployed yet?  I'm still seeing the error come up from robot uploads.

**Comment by hughsie** [comment]
Eeek, no, sorry. I forgot to do it Sunday. I'll do it now.

**Comment by hughsie** [comment]
Okay, can you try now?

**Comment by superm1** [comment]
Yeap, just kicked the robot again and it uploaded successfully.  Of course still shows the warning in the logs, but it did work.
