### ISSUE TITLE
Dell Latitude 7X90 (7290/7390/7490) missing 1.8.0 BIOS

### ISSUE THREAD

**Issue by posto** [hughsie/lvfs-website#263]
LVFS page shows latest version as `1.7.2` while on Dell's website version `1.8.0` is available:

* Link to firmware update at OEM website
Driver list: https://www.dell.com/support/home/us/en/04/product-support/product/latitude-14-7490-laptop/drivers
BIOS details: https://www.dell.com/support/home/us/en/19/drivers/driversdetails?driverid=yhdwy&oscode=wt64a&productcode=latitude-14-7490-laptop
Direct download link: https://downloads.dell.com/FOLDER05386749M/1/Latitude_7x90_1.8.0.exe

* Firmware release date (if available on OEM website)
`22 Jan 2019`

* Link to the device page on LVFS.
https://fwupd.org/lvfs/device/a86a3f07-b7d3-4545-9238-0274fc1ba682

**Comment by superm1** [comment]
Thanks, I'll get this to the right folks.

**Comment by superm1** [comment]
Should be in stable now
