### ISSUE TITLE
Missing firmware for Dell Inspiron 15 17 5575/5775

### ISSUE THREAD

**Issue by mainmachine** [hughsie/lvfs-website#267]
For missing firmware please provide the following items:

https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverid=8mtf8&oscode=biosa&productcode=inspiron-15-5575-laptop

Released 25 Feb 2019

I don't believe there is a device page in LVFS

**Comment by hughsie** [comment]
@superm1

**Comment by superm1** [comment]
Inspiron platforms aren't typically posted to LVFS (you can see the list that is supported on https://fwupd.org/vendorlist)
