### ISSUE TITLE
missing firmware dell latitude e7250

### ISSUE THREAD

**Issue by natxo** [hughsie/lvfs-website#268]
For missing firmware please provide the following items:

* Link to firmware update at OEM website

https://www.dell.com/support/home/nl/nl/nldhs1/product-support/servicetag/1b0f662/drivers

* Firmware release date (if available on OEM website)
A20, 30 October 2018

* Link to the device page on LVFS.
https://fwupd.org/lvfs/search?value=e7250

**Comment by superm1** [comment]
The e7250 doesn't support UEFI capsule updates, so it can not be supported by LVFS.
