### ISSUE TITLE
https://fwupd.org/users should probably be updated

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#27]
I think a lot has changed in fwupd since that page was first written.

1. D-Bus API isn't something apps should directly be doing (they should be accessing via a fwupdclient)
2. fwupdmgr has a ton of client features that aren't mentioned.  Rather than duplicating in a bunch of places, I think it would be useful to offer this: 
```
# fwupdmgr refresh
# fwupdmgr update
```
Indicating that would update all supported devices from LVFS.
For additional options go to wiki page or `README.md` or similar.

3. User interaction probably belongs in developer page not user page.
4. Trusted keys should call out that the only included key is the LVFS key by default.
5. LVFS remotes should be mentioned.

**Comment by hughsie** [comment]
I'm pretty rubbish at prose like this. Do you have anyone non-technical that you could ask to review this?

**Comment by hughsie** [comment]
I was thinking about this a bit today. Would it be clearer if the fwupd-specific content got split off somewhere else, and only content on the LVFS was a simple high level overview of fwupd and mostly concentrated on the vendor tasks? It seems the LVFS should be a place for vendors, and the fwupd info better belongs on a wiki page or something.

**Comment by superm1** [comment]
I'm fine with either approach.  Keeping it in a wiki really does make it easier to update with WYSIWYG markdown preview editors and such.  I'm a fan of that in that regard.
