### ISSUE TITLE
Cross / Check icons not displayed correctly in Firefox

### ISSUE THREAD

**Issue by FloEdelmann** [hughsie/lvfs-website#270]
In Firefox, the vendor list is unusable because the icons are not displayed correctly:

![Screenshot_2019-03-09_13-27-01](https://user-images.githubusercontent.com/202916/54071630-78fa8d80-426f-11e9-9631-7d5adb4b44f0.png)

In Chromium and Inkscape, they look like they should.

**Comment by hughsie** [comment]
On Sat, 9 Mar 2019 at 12:30, Flo Edelmann <notifications@github.com> wrote:

> In Firefox, the vendor list is unusable because the icons are not
> displayed correctly:
>
Hmm, even a simple svg like https://www.fwupd.org/img/tick.svg is failing
to load. Do you know what I'm doing wrong?

Richard.

**Comment by superm1** [comment]
It looks like the icon on the main page of the ghost (related to the spectre notification) has the same issue in FF.
