### ISSUE TITLE
Updating changelog for composite firmware is confusing

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#289]
Visiting the Problems page of a composite firmware that needs updates shows a list of items needing release descriptions but you can't tell which is which.

It's just this message a bunch of times:
```
No valid update description | All components should have a suitable update description before a firmware is moved to stable.Release description is missing
-- | --
```

Pressing the details button for any given update, you can't tell which firmware component it's operating on unless you scroll to the bottom of the page to find the breadcrumb.

I think it would be worth making two changes:
* On the problems page mention which component it is
* On the update page, move the breadcrumb to the top or at least mention the component on the top.

**Comment by hughsie** [comment]
What about something like this?

![Screenshot from 2019-03-28 17-17-28](https://user-images.githubusercontent.com/151380/55178501-6ba13680-517d-11e9-9cca-e0ac6927587e.png)

As for the breadcrumb, I'm hoping to do a bit more of a UI refresh when we rebrand the website.

**Comment by superm1** [comment]
I'd rather see the title if possible in the release description is missing.  The people who are filling it out are not going to know what that means.
Maybe something like:

```
Release description is missing: USB 3.1 Gen2 hub (com.dell.*)
```

**Comment by hughsie** [comment]
Covered on the theme issue. Closing.
