### ISSUE TITLE
Dell XPS 13 9343 System BIOS A19

### ISSUE THREAD

**Issue by pdecat** [hughsie/lvfs-website#294]
For missing firmware please provide the following items:

* Link to firmware update at OEM website: https://www.dell.com/support/home/us/en/19/drivers/driversdetails?driverid=trf18&oscode=wb64a&productcode=xps-13-9343-laptop

* Firmware release date (if available on OEM website): 15 Feb 2019

* Link to the device page on LVFS: Not listed yet.

> Version: A19
> Fixes:
> - Fixed an issue with Secure Boot Option ROM Signature Verification.
> Release date: 15 Feb 2019
> Importance: Urgent

**Comment by superm1** [comment]
This system isn't supported by fwupd and LVFS. Please download the BIOS manually to a USB disk to do the updates from F12 POST menu.

More details here:
https://www.dell.com/support/article/us/en/04/sln171755/updating-the-dell-bios-in-linux-and-ubuntu-environments?lang=en#updatebios2015

**Comment by pdecat** [comment]
Too bad 😪

Thanks anyway!
