### ISSUE TITLE
Visiting https://fwupd.org/lvfs/firmware is taking a long time

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#298]
I took a stopwatch from when I hit enter until the page finished loading.  It was 10.4s to load it.

This is sure to only get worse as more and more devices and firmwares are supported, so I was wondering if it there is a good way to get ahead of it.

My initial idea was to show something like this:
* Show a search box to search strings
* Show last 20 modified devices (eg have newer firmware uploads)
* Offer a link to show all devices
* Offer a link to show all firmware for all devices

At least that should be less of a DB hit and hopefully speed things up quite a bit.

**Comment by hughsie** [comment]
I guess you've got one of the more active vendors; 10s is waaaay too much. I've experimented with the dashboard, but I'd like to explore a bit what you actually do with the firmware view... can you share what you typically use it for?

**Comment by superm1** [comment]
I think the "main" use case I'm aware of is that an ODM uploads a firmware to the OEM account and you need to go find it and modify it/promote it.

The other use case I know of is upload a firmware, wait for tests to pass, go back to that page and find it again and do similar.

In general seeing all the firmware probably is not something useful, especially since that all is on the telemetry pages.

**Comment by hughsie** [comment]
Does the list of firmware on the new dashboard page help some of that? https://fwupd.org/lvfs/dashboard

**Comment by superm1** [comment]
That page takes 11.6 seconds..

**Comment by superm1** [comment]
But if that page can be sped up, I think it does help with the primary use case people have.  It would be a good landing page after login for example I think.

**Comment by superm1** [comment]
Playing with it, it seems like it's not giving correct data though.  It's showing uploads that are definitely way older as "Recent" uploads.

**Comment by hughsie** [comment]
> That page takes 11.6 seconds..

Eeeek. Willfix!

**Comment by superm1** [comment]
> Playing with it, it seems like it's not giving correct data though. It's showing uploads that are definitely way older as "Recent" uploads.

Is this personal data?  I guess I'd expect it to be a "vendor" recent uploads rather than personal recent uploads.

**Comment by hughsie** [comment]
> Willfix!

https://github.com/hughsie/lvfs-website/pull/299 helps a lot!

**Comment by superm1** [comment]
Assuming these already deployed right?
* All firmware page seems the same; 10.98s in my stopwatch just now.
* Dashboard is certainly a lot faster; 3.78s in my stopwatch

Can you configure the dashboard to show recent uploads for the vendor rather than individual recent uploads?  I think that would make it more useful for the situation of ODM uploads OEM promotes.

**Comment by superm1** [comment]
Since this page has been split up now, I think this issue can be closed.
