### ISSUE TITLE
DFU check is running on non DFU firmware

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#302]
I notice this for: https://fwupd.org/lvfs/firmware/1915/tests

![image](https://user-images.githubusercontent.com/494526/55482381-09678c00-55ea-11e9-96ab-657bed5131e5.png)

Not sure why though, there are no DFU in there...

**Comment by superm1** [comment]
Perhaps related; that same upload has all the protocols set wrong even though they were configured in the metainfo.xml.

**Comment by superm1** [comment]
I hand corrected them though

**Comment by hughsie** [comment]
How random, they all get set as the thunderbolt protocol... I'll investigate.

**Comment by hughsie** [comment]
Deployed now, thanks for opening the bug. I can't understand the DFU bit, but what we're doing now certainly works for me.

**Comment by superm1** [comment]
Thanks~
