### ISSUE TITLE
New theme issues

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#307]
I noticed on the affiliates page part of it doesn't render right:
![Screenshot from 2019-04-05 08-12-26](https://user-images.githubusercontent.com/494526/55630151-980b1300-577a-11e9-8ad9-745f0f3b2a6b.png)

Vendor event log for "last 30 days" and "all" both never loaded for me.  I let it spin for at least 30+ seconds on both of them.
After a while all returned
``` Try refreshing the page, or going back and attempting the action again. If this problem persists, contact us. 
```

Probably intentional; but I noticed problems header doesn't have (X) in it to show how many things to fix anymore.

**Comment by superm1** [comment]
One more, Downloads page on a component is cutting off
![Screenshot from 2019-04-05 08-20-47](https://user-images.githubusercontent.com/494526/55630627-bcb3ba80-577b-11e9-832b-5cc989d91f21.png)

**Comment by superm1** [comment]
Sample from the above to demonstrate: https://fwupd.org/lvfs/firmware/1915/analytics/clients

**Comment by hughsie** [comment]
> I noticed problems header doesn't have (X) in it to show how many things to fix anymore.

Intentional indeed. Keep the issues coming, thanks!

**Comment by superm1** [comment]
In that problems page we had talked about making it clearer which component has the problem, as part of theme overhaul can you do that?

On Apr 5, 2019 09:06, Richard Hughes <notifications@github.com> wrote:

[EXTERNAL EMAIL]

I noticed problems header doesn't have (X) in it to show how many things to fix anymore.

Intentional indeed. Keep the issues coming, thanks!

-

**Comment by hughsie** [comment]
Something like this?

![Screenshot from 2019-04-05 16-10-56](https://user-images.githubusercontent.com/151380/55637654-7717e180-57bd-11e9-9952-d67a6e37c8dd.png)

**Comment by superm1** [comment]
Perfect 👌

On Apr 5, 2019 10:11, Richard Hughes <notifications@github.com> wrote:

[EXTERNAL EMAIL]

Something like this?

[Screenshot from 2019-04-05 16-10-56]<https://user-images.githubusercontent.com/151380/55637654-7717e180-57bd-11e9-9952-d67a6e37c8dd.png>
