### ISSUE TITLE
Missing Dell Latitude 7370 1.14.4

### ISSUE THREAD

**Issue by moolinet** [hughsie/lvfs-website#31]
Dell released a month ago a new Latitude 7370 BIOS (1.15.3) to the address the Meltdown/Spectre issues:
https://fwupd.org/lvfs/device/51d41d4e-1a18-49fe-9973-5188425d3c56
Same goes for other laptop models from Dell.

This firmware has issues and has since then been removed from Dell's support page.

The previous stable version is 1.14.4:
http://www.dell.com/support/home/ch/fr/chbsdt1/product-support/product/latitude-13-7370-laptop/drivers

The LVFS currently only has an older version of the firmware: 1.12.4
https://fwupd.org/lvfs/device/51d41d4e-1a18-49fe-9973-5188425d3c56

Trying to downgrade from 1.15.3 to 1.12.4 with the fwupdmgr tool doesn't work:

```
$ sudo fwupdmgr --allow-reinstall --allow-older install 3bc2b4fff99f6980b479d86cfffcbcee84245bea-firmware_Latitude_7370_1.12.4.wu.cab
 * Decompressing firmware
Specified firmware is older than the minimum required version '0.1.15.3 < 0.1.12.4'

```

Could these packages be updated to:
- allow downgrade of BIOS version specifically in the Meltdown/Spectre context
- deploy the currently stable version of the BIOS (1.14.4)

Thanks

**Comment by superm1** [comment]
Downgrade is controlled by the value in the EFI system resource table (ESRT).  In the case of security updates it's typically programmatically disabled.  So for a downgrade you'll have to do it from the F12 POST menu.  Follow these [directions ](https://www.dell.com/support/article/us/en/04/sln171755/updating-the-dell-bios-in-linux-and-ubuntu-environments?lang=en#updatebios2015)to put the executable on a USB disk or ESP for downgrading.

**Comment by moolinet** [comment]
Ok.

Well unfortunately in my case the classic flashing method via the BIOS flashing tool doesn't work.
Since the last firmware update the laptop in question has power-on issues (very long to power on. doesn't power on if the AC is plugged in. standby mode simple reboots the laptop. starting the flashing from BIOS tool simply reboots the laptop)
I have a ticket open with Dell for this. They want to replace the motherboard.

In regard of the downgrade question via fwupdmgr : 
I understand the security policy. But this firmware was automatically pushed by Ubuntu beginning of January. So potentially lots of people out there with a bad firmware that has been rolled back.
I don't understand the specifics of EFI/ESRT but I do see good reason for a security exception to allow this downgrade. 

here's the output on my laptop:
```
$ sudo fwupdmgr get-devices
UEFI-51d41d4e-1a18-49fe-9973-5188425d3c56-dev0
  Guid:                 51d41d4e-1a18-49fe-9973-5188425d3c56
  DisplayName:          Latitude 7370
  Provider:             UEFI
  Flags:                internal|allow-offline|require-ac
  Version:              0.1.15.3
  VersionLowest:        0.1.15.3
  Created:              2018-01-30
  Trusted:              none
```

I gues we can't downgrade because VersionLowest was set to 0.1.15.3
Is the ESRT read-only?
Could this have been avoided by setting VersionLowest to the previous version in the upgrade package?

**Comment by superm1** [comment]
Regarding your issue described above, have you already tried to invoke [BIOS recovery](https://www.dell.com/support/article/us/en/04/sln300716/bios-recovery-options-on-a-dell-pc-or-tablet?lang=en)?  Support may have already offered that before a motherboard replacement, but if not you may consider trying that first.

The ESRT (Which contains a field that corresponds to VersionLowest) is dynamically built by the BIOS at bootup, fwupd and fwupdate just read the values in it.

**Comment by moolinet** [comment]
Ok I didn't know about BIOS recovery

I was able to rollback to the previous BIOS version (1.12.4) although that didn't resolve the power-on issues. 
I'm still unable to use the flash update tool (after choosing the new BIOS file, starting the flashing just reboots the laptop)

Choosing BIOS recovery instead of rollback brought me back to 1.15.3 
with no improvement either.

Thanks for the tips.

**Comment by superm1** [comment]
If you can get into BIOS setup try to reset defaults to see if that helps.  It should re-initialized the SPI and if it's not a hardware problem fix your issues.

I'm however still going to keep this issue open until we have that firmware (or something newer) uploaded to LVFS.

**Comment by moolinet** [comment]
ok
went into the BIOS
-> restaure defaults
-> factory settings

then tried to use the flash update tool again.
no improvement. the system simply reboots.
and I still have my power-on oddities: laptop only boots when AC power is disconnected (direct or via USB-C hub) 

Dell technician should come today or tomorrow.

**Comment by moolinet** [comment]
replacing the mainboard fixed my specific issue.

updated manually to 1.14.4 as the package is not available on LVFS
the 1.15.3 package is still on LVFS but this time my Ubuntu hasn't tried to automatically upgrade to this package.

**Comment by superm1** [comment]
Glad to hear that fixed your problem.
OK well let's keep this open until the new version is on LVFS.

**Comment by superm1** [comment]
It's there now.

**Comment by moolinet** [comment]
this morning:
on https://fwupd.org/lvfs/device/51d41d4e-1a18-49fe-9973-5188425d3c56
the last good one (1.14.4) has not been published
1.15.3 is now "stable" and not "testing" anymore

I also see that the 1.15.3 has been refreshed on the Dell support site:
http://www.dell.com/support/home/ch/fr/chbsdt1/product-support/product/latitude-13-7370-laptop/drivers

but after doing:
```
$ sudo fwupdmgr refresh
$ sudo fwupdmgr get-updates
Latitude 7370 has firmware updates:
ID:                  com.dell.uefi51d41d4e.firmware
GUID:                51d41d4e-1a18-49fe-9973-5188425d3c56
Version:             0.1.15.3
Checksum:            c2126b58b4685e5ceb2a96d1eede3dfeac0c27c5
Checksum Type:       sha1
Location:            https://fwupd.org/downloads/68afc00fa79f4b3b71cdb81f9d52e1b2538bc585-firmware_Latitude_7370_1.15.3.wu.cab
```
the download location is pointing to the "old" 1.15.3 package
sha1 checksum is the same as the old package
