### ISSUE TITLE
https://fwupd.org/lvfs/telemetry times out

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#311]
I'm still not able to visit https://fwupd.org/lvfs/telemetry anymore, over 30 seconds and no results.

Is this maybe another one that data needs to be moved to cron and then mention on the page it's snapshot data?

**Comment by hughsie** [comment]
We certainly need to move this to cron generation. Next week :)

**Comment by hughsie** [comment]
I was thinking this a bit today. Showing a **huge** table isn't awesome UX. Can you share what you actually use the analytics table _for_? I use it to see if any firmware has more failed than success reports. I don't want to just recreate the existing table and make it load faster if it's not useful in it's current form.

**Comment by superm1** [comment]
I believe this is sorted now with the cron stuff.
