### ISSUE TITLE
Theme problems part 3

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#312]
I noticed that this page is rendering wrong
https://fwupd.org/lvfs/firmware/1919/components

![image](https://user-images.githubusercontent.com/494526/55653693-e9d08f00-57b4-11e9-8a00-6f2237823ca4.png)

I'm also noticing the -> Testing and ->Stable buttons missing on firmware that should be promotable (all problems solved) like this:
https://fwupd.org/lvfs/firmware/1915

**Comment by superm1** [comment]
> I'm also noticing the -> Testing and ->Stable buttons missing on firmware that should be promotable (all problems solved) like this:

Oh wait, it's on a new tab.  Hmm.

To avoid confusion, I wonder if you should move the "Current Target" line into the "Target" tab then.

**Comment by hughsie** [comment]
> this page is rendering wrong

Weird, I don't see that. What browser?

**Comment by superm1** [comment]
Chrome 73.0.3683.86

**Comment by hughsie** [comment]
Do all the other firmwares show the same for the component tab, or just that one?

**Comment by superm1** [comment]
Yeah everything I've thrown at it so far is showing that
