### ISSUE TITLE
dell-embargo remote metadata broke

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#323]
When trying to render it the following error is occurring in browser:

```
error on line 1 at column 1: Encoding error
```

This error in fwupd
```
Error on line 1: char 1: Document must begin with an element (e.g. <book>)
```

**Comment by hughsie** [comment]
Can you send me the file by email? It works here even xmllint says it's fine...

    09:26:58:0684 XbSilo               compiling /var/lib/fwupd/remotes.d/dell-embargo/metadata.xml.gz:ctime=1556616418.320285:func-id=AppStreamUpgrade@3:value=/var/lib/fwupd/remotes.d/dell-embargo/metadata.xml.gz:value=dell-embargo…
    ...
    09:26:58:0799 XbSilo               0.24ms      query on / with `components/component` limit=0 -> 461 results
