### ISSUE TITLE
Testing XML metadata shows up as poorly formed XML

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#33]
Using xml minidom:
```
#!/usr/bin/python3
from xml.dom.minidom import parseString
import gzip

xml_file="firmware-testing.xml.gz"
with gzip.open(xml_file, 'rb') as f:
    dom = parseString(f.read())
```

```
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    dom = parseString(f.read())
  File "/usr/lib/python3.5/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 24, column 72
```

Looking at the XML metadata that's this line:
```
        <checksum type="sha1" filename="Firmware_SF30&SN30_Pro_V1.23.dat" target="content">c0fa5454933e5525a530a144c81a58d0e9ecb952</checksum>
```

It looks like it's not properly escaping the **&** character.
I checked the source XML that it's built from to see if it also suffers (https://github.com/hughsie/8bitdo-firmware/blob/master/releases/SF30_Pro-SN30_Pro/1.23/sf30sn30pro.metainfo.xml#L32) but the problem only exists in the checksum generated by LVFS it seems.

**Comment by hughsie** [comment]
Wasn't this fixed with the move to using appstream-glib? Do you have a URL to the metadata please?

**Comment by superm1** [comment]
Came from here: https://fwupd.org/downloads/firmware-testing.xml.gz

**Comment by hughsie** [comment]
Ohh dear, I see the same thing locally.

**Comment by hughsie** [comment]
Okay, new libappstream-glib deployed straight to production (!), metadata regenerated and it seems to work. Panic over, and time to sleep :)
