### ISSUE TITLE
Dell Optiplex 7050 firmware needs updating

### ISSUE THREAD

**Issue by kiwidavenz** [hughsie/lvfs-website#34]
Version 1.5.2 is latest at fwupd.org and version 1.7.6 is available from Dell's support site.

For missing firmware please provide the following items:

* Link to firmware update at OEM website
  https://www.dell.com/support/home/us/en/04/Drivers/DriversDetails?driverId=8P0V0

* Firmware release date (if available on OEM website)
  12 Dec 2017

* Link to the device page on LVFS.
  https://fwupd.org/lvfs/device/4fed6c9d-22b0-4731-a074-084ba68b492a

There also appears to be a duplicate entry for the Dell Optiplex 7050
https://fwupd.org/lvfs/device/10c40550-3da1-44aa-8332-74d09bd1b14f

**Comment by superm1** [comment]
This is the same problem as #31 where the "newer" firmware was pulled back due to Intel recommending everyone to pull spectre microcode updates.  It may not be fixed until the next BIOS with spectre microcode updates.

**Comment by superm1** [comment]
1.7.9 is up there now.
