### ISSUE TITLE
Uploads are failing

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#36]
I've gotten word that pretty basic capsules are failing to upload.

CAB File:
```
$ gcab --list firmware.Latitude_5X90_1.1.8.wu.cab 
DriverPackage\firmware.bin
DriverPackage\firmware.inf
DriverPackage\firmware.metainfo.xml

```
This is the error:

> No firmware.bin found in the archive

Here's a sample:
https://dell.box.com/s/cgq4xqjs8le30rsrqghnv9yedr3759s6

**Comment by hughsie** [comment]
Two things that stick out:

 * It's got path (can fix)
 * It's got two folders, which is a little unusual (although shouldn't be a problem)

I'll test and fix when I'm done with the school run.

**Comment by hughsie** [comment]
Backslashes!

**Comment by superm1** [comment]
I'm guessing this was after moving to appstream glib? The cab file should be same format that we've normally done cab files.
