### ISSUE TITLE
Add new login type specifically with telemetry permission

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#38]
At least in the way that we plan to use telemetry the people who will be looking at telemetry data won't be doing uploads or deleting anything.  They would only be looking at the results (and potentially success/fail).

So can you create a 3rd login type that has qualities like that?  I'd rather not give the QA login out in that scenario.

**Comment by hughsie** [comment]
Got any ideas on a name for the userclass?

**Comment by superm1** [comment]
analytics?

**Comment by hughsie** [comment]
is_analytics? That's one thing the new class would allow, not sure that works. is_viewer? is_analyst? is_manager?

**Comment by superm1** [comment]
I think `is_viewer `or `is_analyst `probably describes them most accurately.  Read only accounts.
