### ISSUE TITLE
Restrict upload abilities by vendor ID

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#4]
At least for some device types (such as DFU or USB) it makes sense to only allow vendors with matching VID to be able to upload devices to mitigate the problem of a potentially compromised account being able to compromise USB devices.

**Comment by hughsie** [comment]
What do you think about these branches?

**Comment by superm1** [comment]
I think that does a pretty good job in limiting this on both sides.  The only corner case that comes to mind is what happens if a FW update is distributed by an OEM but uses the vendor ID of a partner?
The 2 examples that comes to mind are:
1. with this Logitech stuff there is at least one receiver with a Logitech VID, but a Dell PID. 
2. If Synaptics ends up supporting more than Dell systems later, it might fit into this too since everyone uses the Synaptics VID but the payloads are distributed by OEM's. (I know you're not creating a VID right now for Synaptics plugin).

This is probably not going to happen frequently, but how about instead of restricting upload - restrict upload directly to stable and restrict promotion to stable.

Then at least embargo and testing could still be used, and if the corner cases arise raise a github issue when they come up.


UEFI is currently left out, but I think it would also make sense to have something similar there to prevent any potential collisions. You're already using the quirk table to look at the app ID prefix.  How about limiting the app prefix that can be uploaded/promoted by individual accounts to match that too?
This would require probably documenting the approach of:
`com.$OEM.uefi` to be universally used as the prefix, and for the first word in smbios system vendor data to match that $OEM name.

**Comment by hughsie** [comment]
I think in the case of the OEM, I'd be happy just to add the partner vendor ID to the list -- I think it should be a pretty low bar to request another VendorID to be added with a suitable explanation.

Also, we're not actually preventing upload -- you can still upload anything to the LVFS for any vendor ID -- we're just restricting what can be deployed using fwupd. There's no way of securely saying "This is for vendor X" in the metainfo file that can't be spoofed. Unless I'm missing something. This is why we're ensuring the metainfo *doesn't* contain the Vendor ID and we're adding it into the destination AppStream at generation time.

I think UEFI is  slightly special case as we have the secure check on the EFI binary itself. That said, I guess using the HardwareID or maybe just the DMI system vendor might make sense. I'll have a think about UEFI tonight.

**Comment by hughsie** [comment]
Except, thinking about this a bit more, the restricted vendor_ids property should be assigned to the qa_group, rather than the username. I'll rework the patch somewhat.

**Comment by superm1** [comment]
The part for UEFI that might lead to problems is if multiple entries are exporting into ESRT and one is distributed directly by that vendor rather than the system vendor.  At least today I don't know anyone doing this, but that's a "possibility" that could lead to a potential breakage later if adopted.
