### ISSUE TITLE
Perhaps offer the user a resolution for known bugs

### ISSUE THREAD

**Issue by hughsie** [hughsie/lvfs-website#43]
Some of the failed reports for firmware are known bugs in libraries. e.g. `/boot/efi/efi/efi` being checked. Maybe we could have some regexes for common problems and return a string to fwupd to show the user? It's obviously going to be untranslated, but better than nothing.

Of course, the other thing we could do is be more aggressive about hard-depending on the fixed versions of libraries, although that doesn't help people with older versions of fwupd installed and no real way to update.

**Comment by superm1** [comment]
The `/boot/efi/efi/efi` thing i'm not sure could be fixed by hard-depending on fixed versions of libraries.  That specific issue is "caused" by Arch allowing users to put ESPs at whatever mount points they want.  It's mitigated by newer versions of fwupdate but those aren't in arch (due to lack of a new efivar version).

I think regexing for common problems and showing the user is the right thing to do though.  I know that Ubuntu does something like that with apport reports when they get really big bugs.  (_If you want to look for sample code that's probably a good starting point_)

Here's my thought on approach:
* I think the right way to do it would be to set up a wiki page to map to each time a new regex is created and in the response back to the client point them to that wiki page.
* On LVFS categorize failures as "Known issues" and "New issues".  Treat them separately so it's easier to look at the outliers.

**Comment by superm1** [comment]
Regarding it being untranslated, another option is to instead of offering a string, `xdg-open `the URL of the wiki page.  At least people can get at google translate etc on the page then.

**Comment by hughsie** [comment]
@superm1 what about something like this?

![screenshot from 2018-02-13 11-43-50](https://user-images.githubusercontent.com/151380/36149487-c97f3156-10b7-11e8-9298-46825aa9830f.png)
![screenshot from 2018-02-13 11-44-04](https://user-images.githubusercontent.com/151380/36149488-c99f931a-10b7-11e8-88e0-ee41f903dfd3.png)
![screenshot from 2018-02-13 11-56-04](https://user-images.githubusercontent.com/151380/36149489-c9bba096-10b7-11e8-826e-3e7de5d3d764.png)
![screenshot from 2018-02-13 11-56-12](https://user-images.githubusercontent.com/151380/36149490-c9d92d50-10b7-11e8-85e3-ff7b737bbe59.png)
![screenshot from 2018-02-13 12-07-53](https://user-images.githubusercontent.com/151380/36149491-c9f1c360-10b7-11e8-97d4-daebb45e8cc3.png)

It's a fully functional prototype at the moment...

**Comment by superm1** [comment]
That looks very similar to what I was envisioning.
A few questions:
1) Would you have all analytics accounts able to create a known issue?
2) would those show up in failures tab?
3) on telemetry view can you please show them separately from unknown failures?

**Comment by hughsie** [comment]
> Would you have all analytics accounts able to create a known issue?

At the moment it's all admin only, making it qa/analytics needs more thinking about to be secure -- e.g. the issue has to be tied to a `group_id`

> would those show up in failures tab?

You mean the `👍 0 👎 0` in the firmware pages? They could do, but I'm not sure how to show that. Ideas welcome.

> on telemetry view can you please show them separately from unknown failures?

If you mean `/lvfs/telemetry` they could do, would we add a column to have `Success, Failed, Failed (Known Issue)`? Better idea for the new header welcome.

**Comment by superm1** [comment]
> At the moment it's all admin only, making it qa/analytics needs more thinking about to be secure -- e.g. the issue has to be tied to a group_id

Not a big deal for now, I guess this can be revisited later if necessary.

>You mean the 👍 0 👎 0 in the firmware pages? They could do, but I'm not sure how to show that. Ideas welcome.

Perhaps a minus sign (or some "flat" emoji)

> If you mean /lvfs/telemetry they could do, would we add a column to have Success, Failed, Failed (Known Issue)? Better idea for the new header welcome.

Yeah. How about "known failures". Or "triaged failures".

**Comment by hughsie** [comment]
> Not a big deal for now, I guess this can be revisited later if necessary.

It would be easier to restrict this to QA users than analytics -- and then you can play with this yourself too. This does lead into a bigger question; do we have to create a "dell" `Issue` that matches on the `qa_group` with `DistroId=arch` and do exactly the same for HP for example? It seems like some of these issues "transcend" the group structure. Maybe QA users could see these read-only, but then we have to be careful showing reports for other vendors firmwares.

I've put the `group_id` in the `Issues` database so we can easily revisit this in the future.

> Perhaps a minus sign

How about `👍 0 👎 0 👋 0` -- as in we've waved to the user that there's a problem.

> known failures

How about `Success, Failed, Issues`? A known issue isn't really a "failure" in my book.

**Comment by superm1** [comment]
How about QA can create issues that are group dependent but admin can promote them to LVFS wide if deemed necessary and safe?
QA wouldn't be able to modify anything LVFS wide and would only see read-only for those regex.

I'd prefer triaged issues over issues. Anything in that section is something already reviewed.

Hand wave makes sense.

**Comment by hughsie** [comment]
> How about QA can create issues that are group dependent but admin can promote them to LVFS wide

Seems pragmatic.

> I'd prefer triaged issues over issues

It ideally needs to be one word to fix in a col-sm-1

**Comment by superm1** [comment]
> It ideally needs to be one word to fix in a col-sm-1

If it needs to be one word, I think I'd still lean on "Triaged".

**Comment by superm1** [comment]
Here's some starter pages for the initial content:
https://github.com/hughsie/fwupd/wiki/LVFS-Triaged-Issue:-Arch:-Old-artifacts
https://github.com/hughsie/fwupd/wiki/LVFS-Triaged-Issue:-Arch:-Invalid-ESP-location

I think mentioning the tags that brought people there will be useful on the page too.

**Comment by hughsie** [comment]
Okay, code deployed, and added both of those, thanks!
