### ISSUE TITLE
502 on device pages

### ISSUE THREAD

**Issue by beanaroo** [hughsie/lvfs-website#44]
* Link to the device page on LVFS.
https://fwupd.org/lvfs/device/34578c72-11dc-4378-bc7f-b643866f598c
https://fwupd.org/lvfs/device/124c207d-5db8-4d95-bd31-34fd971b34f9

![screenshot from 2018-02-07 11-14-13](https://user-images.githubusercontent.com/1748909/35887114-154da4ce-0bf8-11e8-942f-8bc8b8d35839.png)

**Comment by superm1** [comment]
Looks like it's happening on all the lvfs/device/ pages, not just the ones you linked to.

**Comment by superm1** [comment]
This is probably related to the recent permissions overhaul.  it looks like they work fine while logged in.

**Comment by hughsie** [comment]
I've deployed a hotfix to the server. Thanks for reporting!
