### ISSUE TITLE
XPS 9560 Update available

### ISSUE THREAD

**Issue by beanaroo** [hughsie/lvfs-website#45]
For missing firmware please provide the following items:

* Link to firmware update at OEM website
http://www.dell.com/support/home/nz/en/nzdhs1/drivers/driversdetails?driverId=VNN2D

* Firmware release date (if available on OEM website)
12 Dec 2017

* Link to the device page on LVFS.
https://fwupd.org/lvfs/device/34578c72-11dc-4378-bc7f-b643866f598c

**Comment by superm1** [comment]
This is the same problem as https://github.com/hughsie/lvfs-website/issues/31 where the "newer" firmware was pulled back due to Intel recommending everyone to pull spectre microcode updates.

**Comment by superm1** [comment]
1.6.2 is now here: https://fwupd.org/lvfs/device/34578c72-11dc-4378-bc7f-b643866f598c
