### ISSUE TITLE
Dell Precision 5720 Firmware Update

### ISSUE THREAD

**Issue by andypott** [hughsie/lvfs-website#47]
The latest firmware on LVFS is 2.2.2 - 2.3.0 is available on Dell's site

* Link to firmware update at OEM website
http://www.dell.com/support/home/uk/en/ukdhs1/drivers/driversdetails?driverId=HXP5N

* Firmware release date (if available on OEM website)
11 Dec 2017

* Link to the device page on LVFS.
https://fwupd.org/lvfs/device/a5d83d78-dcba-46c0-9ec4-b5d333574bd3

**Comment by andypott** [comment]
2.3.6 has now also been released on Dell's site (on 18 Feb 2018)

http://www.dell.com/support/home/uk/en/ukdhs1/Drivers/DriversDetails?driverId=F2Y13

**Comment by superm1** [comment]
Thanks, i'll follow up with the team.

**Comment by superm1** [comment]
Now available.
