### ISSUE TITLE
Still triggering 50x errors on some upload

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#48]
I got confirmation that the upload is fixed for the simple upload (eg zip with CAT, INF, XML, BIN).
The upload i'm trying to do that is still failing has multiple XML files.

Here is the CAB i'm trying to upload:
https://dell.box.com/s/ygyz8n99iauczgsto12p7dg7o88krb14

**Comment by hughsie** [comment]
Also to note: I'm in the process of converting to use sqlalchemy, which allows us to load a sqlite database rather than mysql. This will let us write tests for the flask service.
