### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by hughsie** [hughsie/lvfs-website#5]
Originally from https://github.com/hughsie/fwupd-website/issues/1, opened by @C0rn3j

Seems like HTTPS work fine with LE certs, [TLS settings are correct although permissive](
https://www.ssllabs.com/ssltest/analyze.html?d=fwupd.org&hideResults=on), but there's no HTTP redirection.

So:

* [x] Redirect all HTTP requests to HTTPS

* [x] Possibly look into using HSTS and joining the [HSTS preload list](https://hstspreload.org/) (browsers with the HSTS header or those who have the updated preload list won't ever try to use HTTP to access the website)

**Comment by hughsie** [comment]
Hmm, I've tried to do HSTS but I'm getting "Error: www subdomain does not support HTTPS" -- any ideas?

**Comment by C0rn3j** [comment]
>Response error: No HSTS header is present on the response.

You need to configure apache to send a HSTS header that applies on all subdomains(! make sure this doesn't break anything for you) for a long time.

https://cipherli.st/

You can see an example of the HSTS header here.

**Comment by hughsie** [comment]
We get a B+ here now: https://observatory.mozilla.org/analyze/fwupd.org -- it would be higher but I need to use Chart.js
