### ISSUE TITLE
Expecting LVFS policy to provide flexibility for vendor to target certain FW version when doing Linux Capsule Update

### ISSUE THREAD

**Issue by GavinChengGao** [hughsie/lvfs-website#52]
This is a very important request, especially for system BIOS firmware. We have encountered a situation that the old early BIOS can be able to trigger the Linux Capsule Update in command line with the latest LVFS package but it won’t work perfectly and even dangerous in the end. Maybe only some of their BIOS data will be flashed unexpectedly or even the system can’t boot up again if user chooses to do it based on an old and early BIOS version or a certain version that happens to not work.
It is hard for us to force all the users to first upgrade to a suggested/validated firmware version and then can safely do the firmware update.  So we’re seeking the possibility of this flexibility for vendor to target certain FW version in fwupd APP policy level and in LVFS distribution policy level. This will give us the control on what firmware versions are allowed to receive and perform the Linux Capsule Update with the latest LVFS package.
Actually Windows Update has provide such flexibility by specifying CHID in their INF files. CHID can be used for targeting certain system models and even certain firmware versions. It’s not just about flexibility but also about security. Please treat this request seriously. I believe other system vendors are also expecting for this.

**Comment by hughsie** [comment]
We already support this. You can add something like this to the metainfo.xml file:

      
      <requires>
        <id compare="ge" version="0.8.0">org.freedesktop.fwupd</id>
        <firmware compare="ge" version="0.1.2">firmware</firmware>
      </requires>

The compare can be any valid AppStream comparison, eg. ge=greater-than-or-equal, glob or even regex=regular-expression

You can use the CHID too, although this requires a significantly newer fwupd:

      
      <requires>
        <id compare="ge" version="1.0.1">org.freedesktop.fwupd</id>
        <hardware>6de5d951-d755-576b-bd09-c5cf66b27234</hardware>
      </requires>
