### ISSUE TITLE
Require different non-QA LVFS accounts in one group to have only access to their own project LVFS package separately

### ISSUE THREAD

**Issue by GavinChengGao** [hughsie/lvfs-website#53]
As the title says, we have applied multiple non-QA LVFS accounts in one group and found that any one of the accounts can have access to all the project packages on LVFS web site. Please limit each account to its own pakcages for security and better management.

**Comment by hughsie** [comment]
@superm1 do you require that ODMs are able to see other ODMs firmware (for the same qa_group) or would this change break your workflow?

**Comment by superm1** [comment]
No concerns if you adjust this.

**Comment by hughsie** [comment]
This is slightly more involved, as we don't actually keep track about which firmware is uploaded by each user. We keep track of the QA group.

To fix this we need to do a few things:

 * Add a `owner_username` text field to each firmware
 * Use the event log to populate this for existing firmware
 * Add a page that allows the admin/qa user change the owner of the firmware
 * Restrict the permission checks to use `owner_username` for non-QA users
 * Only show firmwares where `g.user.username == fw.owner_username` for non-QA users

Not trivial, so next week I guess.

**Comment by superm1** [comment]
It also then get confusing I suppose with what users with is_analyst permission can see.  I would say probably let is_analyst permission see all uploads (they're going to need to be able to see statistics and dig into failures).
