### ISSUE TITLE
XPS 9360 Update available

### ISSUE THREAD

**Issue by leogrange** [hughsie/lvfs-website#54]
For missing firmware please provide the following items:

* Link to firmware update at OEM website
[http://www.dell.com/support/home/us/en/19/drivers/driversdetails?driverId=YFTT1](url)

* Firmware release date (if available on OEM website)
2.4.2

* Link to the device page on LVFS.
[https://fwupd.org/lvfs/device/48af7d21-3145-4f5e-b1b4-c8fc67b6e646](url)

**Comment by superm1** [comment]
Actually 2.4.2 is available here:
https://fwupd.org/lvfs/device/5ffdbc0d-f340-441c-a803-8439c8c0ae10

There is a transition BIOS posted that will bring you between them that you linked.
