### ISSUE TITLE
Tiny issues showing up with new deployment

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#58]
* Graphical arrows are showing up in wrong place for failed now:
![image](https://user-images.githubusercontent.com/494526/36172495-ae85a9f2-10cb-11e8-95c8-a8ea67a25c93.png)

* Triaged count on Telemetry page didn't increment for old reports

**Comment by hughsie** [comment]
Okay, 9 reports auto-fixed up on the LVFS.
