### ISSUE TITLE
Allow blocking specific user agents

### ISSUE THREAD

**Issue by hughsie** [hughsie/lvfs-website#61]
The ability to restrict firmware to specific versions of fwupd and the existing firmware version was added to fwupd in v0.8.0. This was added so that you could prevent the action if the upgrade was going to fail, either because an older fwupd didn't support the hardware, or if the upgraded-from firmware had a broken self-updater. The former solved by updating fwupd, the latter solved by following the vendor procedure to manually flash the hardware, e.g. using a DediProg to flash the EEPROM directly.

Although 0.8.0 was released over a year ago it seems people are still downloading firmware with older fwupd versions:

    MariaDB [lvfs]> SELECT * FROM useragents WHERE value LIKE 'fwupd/0.6%' ORDER BY datestr DESC LIMIT 10;
    +--------------+----------+-------------+------+
    | condition_id | datestr  | value       | cnt  |
    +--------------+----------+-------------+------+
    |        39771 | 20180126 | fwupd/0.6.2 |    1 |
    |        39742 | 20180125 | fwupd/0.6.2 |    1 |
    |        39713 | 20180123 | fwupd/0.6.2 |    6 |
    |        39681 | 20180122 | fwupd/0.6.2 |    3 |
    |        39631 | 20180120 | fwupd/0.6.2 |    4 |
    |        39597 | 20180119 | fwupd/0.6.2 |    1 |
    |        34798 | 20170420 | fwupd/0.6.2 |    1 |
    |        34785 | 20170419 | fwupd/0.6.2 |    6 |
    |        34716 | 20170414 | fwupd/0.6.2 |    1 |
    |        34701 | 20170413 | fwupd/0.6.2 |    1 |
    +--------------+----------+-------------+------+
    MariaDB [lvfs]> SELECT * FROM useragents WHERE value LIKE 'fwupd/0.7%' ORDER BY datestr DESC LIMIT 10;
    +--------------+----------+-------------+------+
    | condition_id | datestr  | value       | cnt  |
    +--------------+----------+-------------+------+
    |        40234 | 20180215 | fwupd/0.7.3 |    4 |
    |        40196 | 20180214 | fwupd/0.7.0 |    2 |
    |        40213 | 20180214 | fwupd/0.7.3 |    1 |
    |        40167 | 20180213 | fwupd/0.7.0 |    8 |
    |        40171 | 20180213 | fwupd/0.7.4 |    2 |
    |        40183 | 20180213 | fwupd/0.7.3 |    3 |
    |        40145 | 20180212 | fwupd/0.7.0 |    8 |
    |        40080 | 20180209 | fwupd/0.7.0 |    2 |
    |        40095 | 20180209 | fwupd/0.7.3 |    1 |
    |        40060 | 20180208 | fwupd/0.7.0 |    7 |
    +--------------+----------+-------------+------+

My proposal would be to prevent people from downloading all firmware with versions of fwupd < 0.8.0. if the firmware has any kind of requirement on the fwupd version.

I think this might also make @GavinChengGao happy.

**Comment by hughsie** [comment]
@superm1 what version of gnome-software is shipped in 16.04 for example? i.e. what gnome-software versions do I need to block too?

**Comment by superm1** [comment]
3.20.5

**Comment by hughsie** [comment]
@superm1 so anything < that is likely to be on the older fwupd too? I think it's very unlikely a user would have updated gnome-software and explicitly not fwupd.

**Comment by superm1** [comment]
Yeah that's a good assumption.
Also Debian has gnome-software 3.22.5 in stable and fwupd 0.7.4.

**Comment by hughsie** [comment]
I've written a bit about this here: https://blogs.gnome.org/hughsie/2018/02/16/lvfs-will-block-old-versions-of-fwupd-for-some-firmware/ to get some kind of wider feedback.

A workaround for xenial users might be if someone at Canonical could include https://gitlab.gnome.org/GNOME/gnome-software/commit/9bf4ecef4daa2d31827810d672458768c3c2a2b3 that changes the user agent in gnome-software package to be gnome-software/3.20.1 fwupd/0.8.3 and I can fixup my patch to read that.

**Comment by superm1** [comment]
@kenvandine is that [commit](https://gitlab.gnome.org/GNOME/gnome-software/commit/9bf4ecef4daa2d31827810d672458768c3c2a2b3) linked above reasonable to bring into gnome-software in xenial?

**Comment by kenvandine** [comment]
I think that makes sense to SRU.  I don't know how trivial of a backport that might be, we'll need to look into that, but I'd suspect it will be fine.

**Comment by kenvandine** [comment]
@superm1 is there a related ubuntu bug filed for this?  If not, could you please open one?

**Comment by superm1** [comment]
@kenvandine here you go: https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1750030

**Comment by kenvandine** [comment]
@superm1 Awesome, I hadn't even noticed that was a backport for 3.20.  That's excellent, I've triaged the bug.  Thanks!

**Comment by superm1** [comment]
Sure.  So @hughsie I'd say adjust your PR to detect that situation too.  I think if you can add it to 3-22, that's what Debian is on and they can probably pick it up in a future stable update too.

**Comment by hughsie** [comment]
@superm1 I've already adapted the patch for the extra fwupd version in the user agent. I can put that patch on all the other branches too; would up to date tarballs for those help or hinder the Ubuntu/Debian updates? The new tarballs would have new translations too.

**Comment by superm1** [comment]
@kenvandine can comment there, not sure.

**Comment by kenvandine** [comment]
For 16.04 I'm happy just taking the patch.  I'm assuming a new tarball might bring in some other fixes as well, which could be good but means more testing for our SRU verification.
