### ISSUE TITLE
Dell OptiPlex 3050 missing firmware update

### ISSUE THREAD

**Issue by kroeckx** [hughsie/lvfs-website#63]
For missing firmware please provide the following items:

* Link to firmware update at OEM website
http://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverId=Y75WC

* Firmware release date (if available on OEM website)
2017-12-05

* Link to the device page on LVFS.
https://fwupd.org/lvfs/device/293af847-1181-443c-8dd4-5d935d9f8ee5
https://fwupd.org/lvfs/device/78db8ddd-e4d9-4074-9ae7-57134f8ff096
https://fwupd.org/lvfs/device/d69fed57-d865-43f6-b7f4-26405b40b646

**Comment by superm1** [comment]
This is the same problem as #31 where the "newer" firmware was pulled back due to Intel recommending everyone to pull spectre microcode updates.  It may not be fixed until the next BIOS with spectre microcode updates.

**Comment by kroeckx** [comment]
The 1.7.4 version is not about spectre but about the Intel ME fixes, and is listed as the latest version.

**Comment by superm1** [comment]
I know, but the 1.7.4 wasn't posted at the time to LVFS and the team isn't currently planning to upload to LVFS until the new fixes for spectre are ready.

**Comment by superm1** [comment]
For now until the team uploads 1.7.4 or later if you would like to do the update with the newer ME, I would recommend you follow the directions here: https://www.dell.com/support/article/us/en/19/sln171755/updating-the-dell-bios-in-linux-and-ubuntu-environments?lang=en#updatebios2015 that let you flash the update from the F12 post menu.

**Comment by kroeckx** [comment]
So 1.7.9 was released on 20 February:
http://www.dell.com/support/home/us/en/04/Drivers/DriversDetails?driverId=285KK

**Comment by superm1** [comment]
Thanks, i'll follow up with the team.

**Comment by superm1** [comment]
I noticed it's a little confusing.  Is your system the 3050 or the 3050 AIO (they're two different ones).

**Comment by superm1** [comment]
1.7.9 is here now.
https://fwupd.org/lvfs/device/293af847-1181-443c-8dd4-5d935d9f8ee5
