### ISSUE TITLE
Known issue needs to match another condition (related to AC power)

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#65]
https://github.com/hughsie/fwupd/wiki/LVFS-Triaged-Issue:-AC-power-required (and LVFS)
Currently says to match on:

`*AC power required`

However I see at least one report that also has this failure:
`"An external power adapter must be connected for the operation to complete."`

**Comment by superm1** [comment]
That error comes from here: https://github.com/hughsie/fwupd/blob/master/plugins/dell/fu-plugin-dell.c#L599

Since it's "Dell" specific plugin rather than the fwupd wide error, if you think I should just make another LVFS known issue for it that points to the same page I'll do that.

**Comment by hughsie** [comment]
I'm not sure you can have two issues that point to the same page... Ill need to fix that first. Either that or we switch to a regex match.

**Comment by superm1** [comment]
I'd say just switch it to a regex match, I don't think it's going to be too common this happens that we have to point two issues to same page.

**Comment by hughsie** [comment]
Do you have more regex skills than me?

**Comment by superm1** [comment]
What are you using for your regex engine in this case?  Like awk just lets me match like this:
```
$ cat test.txt
This AC power required
An external power adapter must be connected for the operation to complete
Don't match me
```

```
$ cat test.txt  | awk '/AC power required/; /An external power adapter must be connected for the operation to complete/ {print}'
This AC power required
An external power adapter must be connected for the operation to complete
```

**Comment by hughsie** [comment]
Done, I was overthinking the regex stuff. The issue was I needed to drop the uefi plugin condition.
