### ISSUE TITLE
Some "Full Reports" have dissapeared

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#69]
At least glancing through these they're gone.
https://fwupd.org/lvfs/firmware/97/analytics/reports/3
https://fwupd.org/lvfs/firmware/371/analytics/reports/3

![image](https://user-images.githubusercontent.com/494526/36605784-6194b5ca-1887-11e8-81d1-b8fa2e09de43.png)

**Comment by hughsie** [comment]
Deployed just now too.
