### ISSUE TITLE
Feature request: "Search" box for platforms

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#71]
I'm sharing a request that's come up internally to let people find platforms/firmware by a search box at the top of the home page.

Visiting /devicelist and searching the page is a bit too difficult was the feedback.

**Comment by hughsie** [comment]
Some initial thoughts:

 * "people" as in random users looking for firmware, or just OEMs with logins?
 * What would be searched? Component <name>'s seem obvious, but what about release notes? GUIDs?
 * Would searching for "foo bar" be an AND search or an OR search?
 * Would we expect "xps" to match a keyword of "xps13"?
 * Would we expect "13" to match "xps13"?
 * Would the results be 'components' or firmware names?
 * What would the ordering of results be?
 * Would we index things in testing+stable, or just do everything and then filter results based on user level?
 * Where would the search entry go? In the page header or in the devicelist page? If the former, will uses expect a google-like search of all the pages on the site? If the latter, we could move the Login/Password entries into a modal behind a [Login] button.

In the coming months we've got quite a few OEMs coming onboard, so the number of devices and firmwares is only going to increase. If nothing else, I'd find this kind of search helpful.

**Comment by superm1** [comment]
I've also noticed /devicelist is taking a longer time to load lately.

For your questions:

* People is "random" people.
* For the need asked for a box with a watermark "Search platforms" would be adequate. I don't think you need to search other fields for now.
* Yes I'd expect XPS to match xps13 
* I wouldn't expect 13 to match xps13.
* I think firmware names would be more obvious.
* I think ordering should be best match
* Yeah I think this should be based on whether logged in or not
* On the header is where it was desired. I think you can water mark the search box with something descriptive to make it clear what it's providing.

**Comment by hughsie** [comment]
Any initial comments? I'd like to polish things up a bit before we get real world testing.

**Comment by superm1** [comment]
It looks like it's just matching title, which seems fine to me.
I don't think it's necessarily useful to strike through the unfound results.
If it's not a performance hit it would be useful to show "Title" and latest version in the table of results.

**Comment by hughsie** [comment]
Okay, comments welcome: https://7bcca6c4-e943-426b-8039-4c024186ee68.pub.cloud.scaleway.com/lvfs/search?value=xps+13

**Comment by superm1** [comment]
Feedback so far:

*Searching for the 3040 is giving different results each time.
*The firmware version returned isn't always the newest.

**Comment by hughsie** [comment]
Both "fixed" but need tests.

**Comment by hughsie** [comment]
I've blogged about this to get some initial data: https://blogs.gnome.org/hughsie/2018/02/28/searching-for-hardware-on-the-lvfs/

**Comment by superm1** [comment]
I got some more feedback.  Here are the two items that were relevant:

> 1.	Searching with “Dell” shows: “Showing 10 of 101 results for dell:” but there is no navigation option to see the list beyond 10 results listed on the page. 

I'm not sure this is doable because LVFS shouldn't know definitively what things are.  It could make educated guesses though:
> 1.	Search by company/vendor works. But, as LVFS is to host firmware for different types of components, it may be helpful to categorize the updates. Eg: BIOS in our case.

**Comment by hughsie** [comment]
> Showing 10 of 101 results for dell:” but there is no navigation option 

I wasn't sure if showing all the results, or paging them, was the right thing to do. It's a bit like google; who looks at page "2" of the search results? You just do another more specific query.

> it may be helpful to categorize the updates

You can do that now; you can either add them as <keywords> in the metainfo.xml file you upload, or you can edit the component keywords in the LVFS web-UI. I'd also be open for a mass-adding for the existing files on the LVFS if you give me a heuristic to use.

**Comment by superm1** [comment]
What field in metainfo would cause this for categorization purposes?   It isn't obvious right now.

**Comment by hughsie** [comment]
I've added an example in https://fwupd.org/metainfo

**Comment by superm1** [comment]
OK i've made some requests to add that field for future binaries that are made.

For mass adding keywords to the old one, I think you can easily look at the title to do it.
* Thunderbolt NVM upgrades obviously have "Thunderbolt" in the title.
* TPM ones have "TPM" in the title
* MST ones have "MST" in the title
* BIOS ones have "System Update" in the title

**Comment by hughsie** [comment]
Yup, we tokenize the titles already. Keywords are rated "better" than the tokenized string matches, so it's still worth having `<keyword>tpm</keyword>` for instance. Keywords are really useful for things you don't want in the title, but still want to match, e.g. `bios`.

**Comment by superm1** [comment]
Then I guess the only important one for a mass add of keywords would be the system update ones.

**Comment by hughsie** [comment]
I can share some of the search results with you off-ticket if you want, but it seems a lot of people are searching for specific Dell hardware using the "model code" e.g. `e6430` -- would it be possible to add those as `<keyword>`'s to the Dell firmware uploads going forward?

As from a UI point of view, I don't think sticking it in the header works UX wise. I'm open for other ideas, including putting it on the front page somewhere.

**Comment by superm1** [comment]
At least for Dell:
The problem I think that's encountered is some platforms us through same BIOS regardless of screen size and others share between multiple systems.

So you'll see the titles "E6x30" to indicate it works on multiple systems.

Prefilling keywords for supported systems might be doable, but yes please share me what systems people have been searching and it will require more internal investigating what we can do.

**Comment by hughsie** [comment]
> some platforms use through same BIOS regardless of screen size

Right, agree.

> So you'll see the titles "E6x30" to indicate it works on multiple systems

Ahh, so from a code point of view it's really `E6*30` or `E6?30`? Maybe we can just add that as a keyword and make the tags use fnmatch rather than a straight match?

**Comment by hughsie** [comment]
Good to close this now? Loads of people are using the search functionality now.

**Comment by superm1** [comment]
Yeah let's adjust of we feel the need later.

**Comment by FireWolf74** [comment]
Ok Boys and girls how do I use that function on my box?  Or is that something that can only be used via the website?

**Comment by superm1** [comment]
You can use the same HTTP request that is performed by the box on https://fwupd.org/lvfs/devicelist and look at the results.

**Comment by FireWolf74** [comment]
Ok superm1,
Still really nothing for my system I guess I'll have to wait.
