### ISSUE TITLE
Performance has decreased significantly

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#73]
I don't think I know exactly when this has happened with many of the recent changes, but at least lately I've noticed most page loads take much longer, even on my corporate internet connection.

For example hitting https://fwupd.org/lvfs/devicelist chrome was quoting me 5400ms until the page rendered.
![image](https://user-images.githubusercontent.com/494526/36692472-bbf58198-1afd-11e8-91e0-ec6cb699f76d.png)

**Comment by hughsie** [comment]
Any other slow pages you've noticed? devicelist is slow for me also, although nowhere near 5s.

**Comment by superm1** [comment]
Some loads it's closer to 4s.
https://fwupd.org/lvfs/firmware is between 3 and 4s.
https://fwupd.org/lvfs/telemetry is between 5 and 6s

**Comment by hughsie** [comment]
A morning of profiling:

    /lvfs/firmware 4015ms -> 700ms (!!)
    /lvfs/firmware/183 173ms -> 170ms
    /lvfs/component/210 131ms -> 119ms
    /lvfs/devicelist 3250ms -> 690ms (!!)
    /lvfs/device/fc30 5500ms -> 625ms (!!)

This is on the deployed instance using my home 300Mbs internet connection. I've not looked at telemetry yet, but if you could check some of those existing fixes work "quick enough" for you I'd be grateful.

**Comment by hughsie** [comment]
And a bit more:

    /lvfs/telemetry 2400ms -> 1300ms

...but this is for the admin user which can see all firmware. Let me know if I've acttually slowed things down when the number of visible firmware files is smaller.

**Comment by superm1** [comment]
It's sped up for me too :)

**Comment by hughsie** [comment]
Okay, good stuff. Feel free to re-open if anything looks sluggish in the future. My ballpark is all pages should render in under 500ms, with the exception of the telemetry pages which are doing a lot more under the covers and used by a lot fewer people.
