### ISSUE TITLE
Potentially use Azure AD for authentication

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#75]
I've been thinking more about the authentication approach used by LVFS today and I'm wondering if it might be worth adding an optional oauth flow in place as well.

At least for my company we do use Azure AD for authentication to some web services apps.

I'm not sure if adding oauth is doable with no changes on my IT's end for Azure AD, but reading through some of the documentation it does seem like "maybe"?
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-appmodel-v2-overview

If that type of approach is supported I think it could make things more secure to create a LVFS user for every person logging in from the organization and auditing against the oauth account rather than the LVFS credential used to log in.

Furthermore configuring which users have promotion permissions outside of embargo can be done separately.

**Comment by superm1** [comment]
That URL was for adding support for both personal and enterprise accounts.  And if you don't support personal accounts (only AD accounts) it seems you can use https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-developers-guide

**Comment by superm1** [comment]
Oh and there's this:
https://github.com/Azure-Samples/active-directory-python-flask-graphapi-web-v2

**Comment by hughsie** [comment]
I think this is in the "nice to have" camp. I'm not terribly familiar with OAUTH and friends, and have heard horror stories where it was implemented wrongly and thus was terribly insecure. I'd like to finish the search code and get the performance up to awesome before attempting something like this.

**Comment by superm1** [comment]
Yeah I think those other two are more important right now.  At least looking at that sample code it looks pretty straightforward to adopt from Microsoft Graph API.

**Comment by hughsie** [comment]
For Dell, we'd have a config section like https://github.com/Azure-Samples/active-directory-python-flask-graphapi-web-v2/blob/master/v2flaskapp.py#L17 -- but that would point to the Dell AD or the login.microsoftonline.com one? If the former I'd need the consumer_secret and consumer_key for the registration surely -- and I'm guessing your IT team wouldn't like that. If it's the latter how would we check the Dell specific "this person still works for us" metadata?

The way I'm seeing it work is to provide a layer "above" the existing LVFS accounts, at least initially.

**Comment by superm1** [comment]
I'm pretty sure you would make an LVFS "app" at apps.dev.microsoft.com.  Then you would keep those secrets related to the app somewhere not in github.

You would point to the Microsoft Graph API.  Then when someone hits the MS graph API MS will check against regular MS accounts or AD accounts.  If there's a hit you get back some data (IIRC company, phone number, email address etc).

When they leave Dell, you should stop getting hits due to the Azure AD replication.

I guess if you want to make the LVFS app in apps.dev.microsoft.com and put it in a test instance I can hit it and you see what you get back from my AD account vs from an MSA account.

**Comment by hughsie** [comment]
I tried this a few hours ago locally, but keep getting the cryptic `error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.` -- I think it's trying to tell me I have to use a https:// URI, but that's going to need a little more time to deploy to the test instance.

**Comment by superm1** [comment]
That's odd because the "sample" for testing shows a redirect URI of `http://localhost:5000/login/authorized`

**Comment by hughsie** [comment]
Okay, randomly, it works this morning. I'll have a think over the weekend how to slot it in to the LVFS.

**Comment by hughsie** [comment]
How is this going to work in practice? Is we use the email address returned by azure, are we going to tag existing user accounts with something like `allowed_to_login_using_azure` or we just let anyone with an existing account on the LVFS do it?

**Comment by superm1** [comment]
Since you've broken it up already that limited accounts can only see their own uploads and upload to Embargo I'd say use this criteria:

- Check the domain of the account.  Does it match a "Group" you support?  If so, make them their own personal "limited" account and log them into the group.
- When logged in with OAuth don't allow setting a password, require login with OAuth (to help with the "Employee leaves the company situation")
- On an admin end allow "upgrading" an account to QA or analytics.
- Still allow OAuth "or" regular login to support allowing ODM to upload to embargo/private, but QA still required to login to promote (and QA will only come in through OAuth flow assuming this works out)
