### ISSUE TITLE
LVFS should enforce firmware files have urgency set on upload

### ISSUE THREAD

**Issue by hughsie** [hughsie/lvfs-website#77]
This allows us to prioritize the notification in gnome-software. An alternative would be to require the urgency is set in the web-ui before moving to testing or stable.

**Comment by superm1** [comment]
I would prefer to see a modal dialog come up when moving to testing/stable, something like this:

**Missing urgency**
This firmware doesn't have an urgency level set.
Please choose the urgency level for this firmware.
1. Required
2. Install when convenient

The remaining problem would be uploads that are uploaded directly to testing/stable.  I don't know how common that is, but the obvious solution is to in the POST have an optional urgency field and if the binary doesn't have urgency set throw an error and complain about the need for that field to be set during upload.

**Comment by hughsie** [comment]
> would be uploads that are uploaded directly to testing/stable

I've been wondering about disabling that for a while now. It's probably not a very good idea generally.

**Comment by superm1** [comment]
Can you check stats if much gets uploaded directly there before making that kind of change?

**Comment by hughsie** [comment]
> Can you check stats if much gets uploaded directly there before making that kind of change?

I can, but tomorrow. I guess there's not much point removing it as an option if a vendor (think smaller vendor, only the one qa user) can just upload to embargo, and then move straight away to testing, then straight away to stable. I guess we could enforce the amount of time it spends in testing (say 1 day?) using the new FirmwareEvent thing we added the other day. I think allowing upload to testing is probably okay to keep, but maybe not stable.

**Comment by hughsie** [comment]
> Enforcing a migration period might just slow things down needlessly.

Yes, perhaps you're right. I do think a warning is a good idea, but a warning that can be ignored.

**Comment by hughsie** [comment]
Something like this?

![screenshot from 2018-03-02 11-07-38](https://user-images.githubusercontent.com/151380/36896331-27cda8dc-1e0a-11e8-9294-4935fe36e722.png)

**Comment by hughsie** [comment]
and

![screenshot from 2018-03-02 13-47-53](https://user-images.githubusercontent.com/151380/36901823-557ed740-1e20-11e8-983b-374f665e9290.png)
