### ISSUE TITLE
Drop usernames and use email addresses everywhere

### ISSUE THREAD

**Issue by hughsie** [hughsie/lvfs-website#82]
At the moment we have three user identifiers used in the database, the `username`, the `email` and the `user_id` integer primary key. When we add OAuth we'll be adding a fourth, an `oauth_id` string as well. This is getting quite confusing and unwieldy in the code, for something that is supposed to be transparent and easy to understand.

My proposal would be to stop using the username for login, and use the email as the user-visible string to represent the user representing the vendor. This causes problems where the email is associated with many different usernames, e.g. `vendor_qa` and `vendor_$odm`. In this case we could use a "fake" email address, e.g. existing_email+foxconn@existing_domain.com and use that for login.

I guess we'd also support using the old username as the way to log in (with an appropriate warning message?) for some time to allow ODMs and OEMs to update any process instructions.

@superm1 Comments?

**Comment by hughsie** [comment]
>When we add OAuth we'll be adding a fourth, an oauth_id string as well

Actually, we can do without the oauth_id if we use userPrincipalName (the email address) although the same problem applies when more than one user "shares" an email address.

**Comment by superm1** [comment]
Yeah something like this will definitely take some time for adjustment to stopping logging in using an ID, so this would need some transitional time period that old logins via username still worked like you're doing for description/urgency.

> Actually, we can do without the oauth_id if we use userPrincipalName (the email address) although the same problem applies when more than one user "shares" an email address.

WIth OAuth how can that happen?  I guess by user you mean "LVFS user account"?  Like currently i'm same contact email for some accounts that are ODM upload only.

I do think switching to "email" logins makes sense though when OAuth is turned on. It is more logical then.  How about for those existing ODM accounts that are upload only just change them over to fake email addresses?
Eg `compal@dell.com`.  Then for some time period allow logging in with: 

- the old account name (Show a warning)
- that fake email (Don't show anything)
- oauth (Don't show anything)

**Comment by hughsie** [comment]
> just change them over to fake email addresses?

This is fine if the LVFS is authenticating old-school style. In the case of using OAuth the userPrincipalName has to match the "fake" email address. So if you've got a user 'Alice' who's trying to log in using alice@dell.com that's not going to match the fake compal@dell.com account and that's going to fail.

I think using "fake" email addresses makes sense as a transitional step (where ODMs are "sharing" a single login) but for OAuth we need the actual email to match. I don't know whether that's the OEM saying to me "please create alice@dell as non-qa account for dell" and allowing Alice to log in using OAuth, or if we just go full throttle and say "accept a login from any @dell.com domain where the user is in a specific domain group".

Maybe that's three "phases":

1. create fake email addresses and deprecate usernames for 6 months
2. accept oauth logins from pre-added users, with the inability to change the LVFS local password
3. accept oauth logins using vendor-specific group rules

**Comment by hughsie** [comment]
I'll close this and we can work on the OAuth one now it's all bundled together.
