### ISSUE TITLE
Not clear how to login using OAuth

### ISSUE THREAD

**Issue by hughsie** [hughsie/lvfs-website#88]
From @superm1:

> I wonder if there is a way to make this more obvious? Some thoughts that can help:
> Split login process along to email and password separately rather than at once. If they fill in the email that matches something oauth only show the appropriate message or redirect.
> Split that login page into a two stage dialog with buttons for "LVFS Username and password" and "Login providers".
> The error message for someone that was supposed to login via oauth doesn't indicate that. It just says invalid username/password. It should probably show something along the lines of "Your account can only be logged in using a login provider".

**Comment by hughsie** [comment]
@superm1 Something like this? Comments welcome.

![screenshot from 2018-03-17 11-26-36](https://user-images.githubusercontent.com/151380/37554823-2578a0be-29d6-11e8-9d2e-965c9d61c202.png)

**Comment by superm1** [comment]
That is an improvement to me. I think between that and an improved error message doe logging into wrong place it should help a lot.

You can obviously monitor logs to see if there is still more confusion arising and more changes can be tweaked later.
