### ISSUE TITLE
Don't delete firmware objects when deleting

### ISSUE THREAD

**Issue by hughsie** [hughsie/lvfs-website#89]
Vendors are allowed to delete firmware -- but those Firmware objects have FirmwareEvents, Events, Reports and Client objects that reference them. It seems somewhat wrong to just delete everything as if the firmware never existed from an audit point of view.

My proposal would be to delete the actual .cab file, and then mark the firmware as deleted in the database and in the admin UI. We'd need to change various dialogs to show what's happened. Comments welcome.

**Comment by superm1** [comment]
I agree with this thought process,, seems sensible to me.
