### ISSUE TITLE
It is too easy to accidentally move a firmware to stable

### ISSUE THREAD

**Issue by gnolsen** [hughsie/lvfs-website#9]
If you accidentally click the '->Stable' button, the firmware is immediately published. And this is point of no return.

It would be nice with an extra confirmation step to minimize the risk of this happening.

**Comment by superm1** [comment]
Probably not the fix you're looking for, but at least there is this now:
https://github.com/hughsie/lvfs-website/issues/16

That will let you demote a firmware back to testing if you accidentally did bring it up to stable.
