### ISSUE TITLE
Logitech Unifying receivers have more recent firmware version

### ISSUE THREAD

**Issue by Ashark** [hughsie/lvfs-website#92]
Logitech Unifying recievers (both RQR12 and RQR24) have more recent firmware than available in lvfs repository.

I have both types of recievers and all set of desktop OSs (Linux, Mac, Windows), so I made several tests.
For my first reciever (RQR12), which has BOT01.02_B0015 bootloader
I could upgrade from stock RQR12.03_B0025 to RQR12.07_B0029 on linux.
But when I use SecureDFU utility (available [here](https://community.logitech.com/s/question/0D531000058b3B7CAI/logitech-response-to-research-findings)) on Mac and on Windows I was able to update to **RQR12.08_B0030**.

For my second reciever (RQR24), which has BOT03.01_B0008 bootloader
I could upgrade from stock RQR24.01_B0023 to RQR24.05_B0029 on linux.
But when I use SecureDFU utility (the same [link](https://community.logitech.com/s/question/0D531000058b3B7CAI/logitech-response-to-research-findings)) on Mac and on Windows I was able to update to **RQR24.06_B0030**.

* Link to firmware update at OEM website
Firmwares are available as binary at [Logitech/fw_updates](https://github.com/Logitech/fw_updates)
There are also even more recent versions there, but they say they are for Unifying recievers with more recent bootloader than mine. I do not know if it is possible to update bootloader. When I did all that experimenting (upgrading/downgrading on linux and upgrading using windows and mac), only fw version was changed, but not bootloader version.

* Link to the device page on LVFS.
https://fwupd.org/lvfs/search?value=unifying

**Comment by xosevp** [comment]
I can confirm that there is new firmware.
I did update it to RQR12.08_B00**30** (bootloader: BOT**01.02**_B0014)

**Comment by ChrisCheney** [comment]
Its another year later and now its 2 revisions out of date. Is this ever going to be updated?

In lvfs:  RQR12.07_B0029

In git: RQR12.09_B0030

**Comment by ChrisCheney** [comment]
It would be nice if 12.08 / 12.09 would be provided since it fixes a security vulnerability.

12.07 only fixes the old 11 advisory not the newer 13 advisory.

[KeyJack Affected Devices](https://www.bastille.net/research/vulnerabilities/keyjack/affected-devices)

[Bastille Threat Research Team Tracking Number 13](https://github.com/BastilleResearch/keyjack/blob/master/doc/advisories/bastille-13.logitech.public.txt)

**Comment by ChrisCheney** [comment]
The security update was provided by Logitech on Dec 5, 2017.

[Logitech Response to Research Findings](https://community.logitech.com/s/question/0D531000058b3B7CAI/logitech-response-to-research-findings)

[RQR12.07 Build 0029](https://github.com/Logitech/fw_updates/blob/master/RQR12/RQR12.07/RQR12.07_B0029.txt)
> Address Bastille security issue #11 unencrypted keystroke injection fix bypass

[RQR12.08 Build 0030](https://github.com/Logitech/fw_updates/blob/master/RQR12/RQR12.08/RQR12.08_B0030.txt)
> - Address Bastille security issue #13 Encrypted Keystroke Injection

[KeyJack Affected Devices](https://www.bastille.net/research/vulnerabilities/keyjack/affected-devices)

[Bastille Threat Research Team Tracking Number 13](https://github.com/BastilleResearch/keyjack/blob/master/doc/advisories/bastille-13.logitech.public.txt)

**Comment by hughsie** [comment]
@mviredaz @ogay can you move the RQR24.06_B0030 and RQR12.08_B0030 firmwares to testing or stable please?

**Comment by ogay** [comment]
@xnlcasad is reviewing it. Nestor could you confirm when the firmwares have been uploaded?

**Comment by xnlcasad** [comment]
We just rebuilt the cabs with [this PR](https://github.com/Logitech/fw_updates/pull/19) from @hughsie that will also close [fwupd 1123](https://github.com/hughsie/fwupd/issues/1123)
Firmware uploaded to lvfs, moved to testing.

**Comment by marty60** [comment]
Is there any firmware that will stop this wireless Logitech mouse from waking up the monitor after exactly 5 minutes? I know it's the unifying receiver that's responsible because when that's disconnected the monitor stays asleep. The only workaround is to delay the monitor shut down until after 10 minutes, then it stays off for the most part, but not always. 

Very annoying and whenever I leave the house the usb mouse cord has to be disconnected to ensure the monitor won't come back on.

**Comment by nightsky30** [comment]
I see that RQR12.08_B0030 and RQR24.06_B0030 .cabs were added on their respective pages, but the device list page is now missing a link to https://fwupd.org/lvfs/device/com.logitech.Unifying.RQR12.firmware

**Comment by hughsie** [comment]
Where do you think there is a missing link?

**Comment by nightsky30** [comment]
Prior to whatever changes were made recently regarding the availability of the Logitech Unifying receivers' firmware there were two links listed with "Unifying Receiver Device Update".

One went to:
https://fwupd.org/lvfs/device/com.logitech.Unifying.RQR12.firmware
The other went to:
https://fwupd.org/lvfs/device/com.logitech.Unifying.RQR24.firmware

Now there is only one page listed that supplies the RQR24 firmware.  The other page exists, but the link was removed.

![Screenshot_2019-04-18_17-37-36](https://user-images.githubusercontent.com/6024315/56395856-ec45d680-6201-11e9-8356-5d6d86b7ffc6.png)

**Comment by bilogic** [comment]
> Is there any firmware that will stop this wireless Logitech mouse from waking up the monitor after exactly 5 minutes? I know it's the unifying receiver that's responsible because when that's disconnected the monitor stays asleep. The only workaround is to delay the monitor shut down until after 10 minutes, then it stays off for the most part, but not always.
> 
> Very annoying and whenever I leave the house the usb mouse cord has to be disconnected to ensure the monitor won't come back on.

That's enlightening! I faced the same problem too and never thought it could be due to logitech!
