### ISSUE TITLE
"Profile" menu doesn't make sense for limited users

### ISSUE THREAD

**Issue by superm1** [hughsie/lvfs-website#97]
Limited users aren't able to do anything in that menu other than log out.

Due to this I'd propose the menu shouldn't be called "Profile", but rather render the name of the user that's logged in (maybe on 2 lines considering people with log names like me).

![image](https://user-images.githubusercontent.com/494526/38143559-a973b342-3406-11e8-9bb6-db786fc568ad.png)

**Comment by hughsie** [comment]
You've not even got the longest name on the LVFS :) What about something like "Account"? The alternative is we just change the "Profile" dropdown to be a "Logout" button.

**Comment by superm1** [comment]
Log out is fine too.
